(()=>{'use strict';
const officialRaw=Array.isArray(window.ER_OFFICIAL_SPECIES)?window.ER_OFFICIAL_SPECIES:[];
const speciesRaw=Array.isArray(window.ER_SPECIES)?window.ER_SPECIES:[];
const pokemonRaw=Array.isArray(window.ER_POKEMON_DATA)?window.ER_POKEMON_DATA:[];
function speciesFallback(){const raw=officialRaw.length?officialRaw:speciesRaw;return raw.filter(r=>Array.isArray(r)&&r.length>=3&&String(r[2]||'').trim()).map(r=>officialRaw.length?({id:Number(r[0]),en:String(r[1]||''),ko:String(r[2]||''),dex:Number(r[3]||0),form:Boolean(r[4]),token:String(r[5]||''),sprite:'',types:[],stats:null}):({id:Number(r[0]),en:String(r[1]||''),ko:String(r[2]||''),dex:Number(r[0])+1,form:false,token:'',sprite:'',types:[],stats:null}))}
function makeStats(r){const s={hp:Number(r[7]||0),atk:Number(r[8]||0),def:Number(r[9]||0),spa:Number(r[10]||0),spd:Number(r[11]||0),spe:Number(r[12]||0)};return Object.values(s).every(v=>v>0)?s:null}
const species=(pokemonRaw.length?pokemonRaw.map(r=>({id:Number(r[0]),dex:Number(r[1]),ko:String(r[2]||''),en:String(r[3]||''),sprite:String(r[4]||''),types:[String(r[5]||''),String(r[6]||'')].filter(Boolean),stats:makeStats(r),form:Boolean(r[13]),token:String(r[14]||'')})).filter(x=>x.id>0&&x.ko):speciesFallback());
function isMega(x){return /^MEGA(?:_[XY])?$/.test(String(x.token||''))||/_MEGA(?:_[XY])?$/.test(String(x.sprite||''))}
function category(x){return isMega(x)?'mega':x.form?'form':'base'}
for(const x of species)x.category=category(x);
const speciesById=new Map(species.map(x=>[x.id,x]));
const formGroups=new Map();for(const x of species){if(!formGroups.has(x.dex))formGroups.set(x.dex,[]);formGroups.get(x.dex).push(x)}
let moves=[],abilities=[];const dataReady={moves:false,abilities:false},dataLoading={moves:null,abilities:null};
const TYPE_ORDER=['노말','불꽃','물','풀','전기','얼음','격투','독','땅','비행','에스퍼','벌레','바위','고스트','드래곤','악','강철','페어리','스텔라'];
const STAT_LABELS=[['hp','체력'],['atk','공격'],['spa','특공'],['def','방어'],['spd','특방'],['spe','스피드']];
const PAGE_SIZE={pokemon:48,moves:80,abilities:80};
const q=document.getElementById('q'),grid=document.getElementById('grid'),empty=document.getElementById('empty'),count=document.getElementById('count'),countLabel=document.getElementById('countLabel'),result=document.getElementById('result'),title=document.getElementById('title'),tabs=[...document.querySelectorAll('.tab')];
const filters=document.getElementById('pokemonFilters'),categoryFilters=document.getElementById('categoryFilters'),typeFilters=document.getElementById('typeFilters'),resetFilters=document.getElementById('resetFilters'),sortPokemon=document.getElementById('sortPokemon');
const backdrop=document.getElementById('detailBackdrop'),detailType=document.getElementById('detailType'),detailTitle=document.getElementById('detailTitle'),detailShort=document.getElementById('detailShort'),detailLong=document.getElementById('detailLong'),detailShortLabel=document.getElementById('detailShortLabel'),detailLongLabel=document.getElementById('detailLongLabel'),detailPokemonExtra=document.getElementById('detailPokemonExtra'),detailFormsSection=document.getElementById('detailFormsSection'),detailForms=document.getElementById('detailForms'),detailClose=document.getElementById('detailClose');
const loadWrap=document.createElement('div');loadWrap.className='load-more-wrap';loadWrap.innerHTML='<div><button id="loadMore" class="load-more" type="button">더 보기</button><small id="loadState" class="load-state"></small></div>';grid.after(loadWrap);const loadMore=document.getElementById('loadMore'),loadState=document.getElementById('loadState');
let view='pokemon',filtered=[],renderedCount=0,tabGeneration=0;const activeCategories=new Set(['base','form','mega']),activeTypes=new Set();
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function current(){return view==='moves'?moves:view==='abilities'?abilities:species}
function bst(x){if(!x.stats)return 0;return x.stats.hp+x.stats.atk+x.stats.def+x.stats.spa+x.stats.spd+x.stats.spe}
function matches(x,term){if(!term)return true;if(view==='pokemon')return x.ko.toLocaleLowerCase('ko-KR').includes(term)||x.en.toLowerCase().includes(term)||String(x.dex).includes(term)||String(x.id).includes(term)||x.types.some(t=>t.includes(term));return x.ko.toLocaleLowerCase('ko-KR').includes(term)||String(x.id).includes(term)||(x.desc||'').toLocaleLowerCase('ko-KR').includes(term)||(x.long||'').toLocaleLowerCase('ko-KR').includes(term)}
function meta(){if(view==='moves')return['기술 도감','불러온 기술','한국어 기술 이름 / 설명 / 기술 ID 검색'];if(view==='abilities')return['특성 도감','불러온 특성','한국어 특성 이름 / 설명 / 특성 ID 검색'];return['포켓몬 도감','불러온 포켓몬·폼','포켓몬 이름 또는 도감 번호를 검색해주세요']}
function spriteUrl(x){return x.sprite?`https://raw.githubusercontent.com/ForwardFeed/ER-nextdex/main/static/sprites/${encodeURIComponent(x.sprite)}.png`:''}
function typeChips(types){return types.length?types.map(t=>`<span class="type-chip" data-type="${esc(t)}">${esc(t)}</span>`).join(''):'<span class="stats-unavailable">타입 데이터 준비 중</span>'}
function statCells(x){if(!x.stats)return '<div class="stats-unavailable">종족값 데이터 준비 중</div>';return `<div class="mini-stats">${STAT_LABELS.map(([k,l])=>`<div><span>${l}</span><b>${x.stats[k]}</b></div>`).join('')}</div>`}
function badge(x){if(x.category==='mega')return '<span class="form-badge mega-badge">MEGA</span>';if(x.category==='form')return '<span class="form-badge">FORM</span>';return ''}
function pokemonCard(x){const img=spriteUrl(x);return `<article class="card species-card is-detail${x.category==='form'?' is-form':''}${x.category==='mega'?' is-mega':''}" role="button" tabindex="0" data-kind="pokemon" data-id="${x.id}" data-category="${x.category}" aria-label="${esc(x.ko)} 상세 보기"><div class="sprite-wrap">${img?`<img class="sprite" src="${img}" alt="${esc(x.ko)}" loading="lazy" decoding="async" fetchpriority="low">`:''}<span class="sprite-fallback">?</span></div><div class="card-copy"><div class="num"><span>No.${String(x.dex).padStart(4,'0')}</span>${badge(x)}</div><div class="ko">${esc(x.ko)}</div><div class="en">${esc(x.en)}</div><div class="type-row">${typeChips(x.types)}</div>${statCells(x)}<div class="detail-hint">${(formGroups.get(x.dex)||[]).length>1?'다른 모습 / 상세 정보':'상세 정보'}</div></div></article>`}
function textCard(x){return `<article class="card move-card is-detail" role="button" tabindex="0" data-kind="${view}" data-id="${x.id}" aria-label="${esc(x.ko)} 상세 보기"><div class="num">${view==='moves'?'MOVE':'ABILITY'} #${String(x.id).padStart(4,'0')}</div><div class="ko">${esc(x.ko)}</div>${x.desc?`<div class="desc">${esc(x.desc)}</div>`:''}<div class="detail-hint">상세 보기</div></article>`}
function updateLoadState(){const total=filtered.length;loadMore.hidden=renderedCount>=total||total===0;loadState.textContent=total?`${renderedCount.toLocaleString('ko-KR')} / ${total.toLocaleString('ko-KR')} 표시`:'';result.textContent=total?`${total.toLocaleString('ko-KR')}개 중 ${renderedCount.toLocaleString('ko-KR')}개 표시`:'0개'}
function appendNext(){if(renderedCount>=filtered.length)return;const next=filtered.slice(renderedCount,renderedCount+PAGE_SIZE[view]);grid.insertAdjacentHTML('beforeend',view==='pokemon'?next.map(pokemonCard).join(''):next.map(textCard).join(''));renderedCount+=next.length;updateLoadState()}
function render(){const rows=current(),term=(q.value||'').trim().toLocaleLowerCase('ko-KR'),m=meta();let out=rows.filter(x=>matches(x,term));if(view==='pokemon'){out=out.filter(x=>activeCategories.has(x.category));if(activeTypes.size)out=out.filter(x=>x.types.some(t=>activeTypes.has(t)));const mode=sortPokemon?.value||'dex';out=[...out].sort((a,b)=>mode==='name'?a.ko.localeCompare(b.ko,'ko'):mode==='bst'?bst(b)-bst(a)||a.dex-b.dex:a.dex-b.dex||a.id-b.id)}filtered=out;renderedCount=0;grid.innerHTML='';count.textContent=rows.length.toLocaleString('ko-KR');countLabel.textContent=m[1];title.textContent=m[0];q.placeholder=m[2];filters.hidden=view!=='pokemon';grid.classList.toggle('moves',view!=='pokemon');grid.classList.toggle('pokemon-grid',view==='pokemon');empty.hidden=out.length!==0;appendNext();updateLoadState()}
function renderCategoryFilters(){if(!categoryFilters)return;const counts={base:0,form:0,mega:0};for(const x of species)counts[x.category]++;const labels={base:'기본',form:'폼',mega:'메가'};categoryFilters.querySelectorAll('[data-category]').forEach(btn=>{const k=btn.dataset.category,span=btn.querySelector('.category-count');if(span)span.textContent=counts[k].toLocaleString('ko-KR');btn.classList.toggle('active',activeCategories.has(k));btn.setAttribute('aria-pressed',activeCategories.has(k)?'true':'false');const text=btn.querySelector('.category-label');if(text)text.textContent=labels[k]})}
function renderTypeFilters(){if(!typeFilters)return;const present=new Set(species.flatMap(x=>x.types));typeFilters.innerHTML=TYPE_ORDER.filter(t=>present.has(t)).map(t=>`<button type="button" class="type-filter${activeTypes.has(t)?' active':''}" data-type="${esc(t)}" aria-pressed="${activeTypes.has(t)?'true':'false'}"><span class="type-dot" data-type="${esc(t)}"></span><span>${esc(t)}</span></button>`).join('')}
function findDetail(kind,id){if(kind==='pokemon')return speciesById.get(id);const rows=kind==='moves'?moves:abilities;return rows.find(x=>x.id===id)}
function renderForms(x){const siblings=formGroups.get(x.dex)||[];detailFormsSection.hidden=siblings.length<=1;detailForms.innerHTML=siblings.length<=1?'':siblings.map(s=>`<button class="form-link${s.id===x.id?' active':''}" type="button" data-id="${s.id}" aria-current="${s.id===x.id?'true':'false'}"><strong>${esc(s.ko)}</strong><span>${esc(s.en)} · ${s.category==='mega'?'MEGA':s.category==='form'?'FORM':'기본'}</span></button>`).join('');return siblings}
function renderPokemonExtra(x){if(!detailPokemonExtra)return;const img=spriteUrl(x),stats=x.stats?STAT_LABELS.map(([k,l])=>{const v=x.stats[k],w=Math.max(2,Math.min(100,(v/255)*100));return `<div class="detail-stat"><span>${l}</span><b>${v}</b><i><em style="width:${w.toFixed(1)}%"></em></i></div>`}).join(''):'';detailPokemonExtra.innerHTML=`<div class="pokemon-detail-overview"><div class="detail-sprite-wrap">${img?`<img class="detail-sprite" src="${img}" alt="${esc(x.ko)}">`:''}<span class="sprite-fallback">?</span></div><div class="detail-pokemon-data"><div class="type-row">${typeChips(x.types)}</div>${x.stats?`<div class="detail-stats">${stats}</div><div class="bst">종족값 합계 <b>${bst(x)}</b></div>`:'<p class="muted">공식 NextDex에 이 모습의 종족값이 비어 있습니다.</p>'}</div></div>`;detailPokemonExtra.hidden=false}
function openDetail(kind,id,keepFocus=false){const x=findDetail(kind,id);if(!x)return;if(kind==='pokemon'){const siblings=renderForms(x);renderPokemonExtra(x);detailType.textContent=`포켓몬 · 전국도감 No.${String(x.dex).padStart(4,'0')} · ${x.category==='mega'?'MEGA':x.category==='form'?'FORM':'기본'}`;detailTitle.textContent=x.ko;detailShortLabel.textContent='영문명';detailShort.textContent=x.en;detailLongLabel.textContent='모습 정보';detailLong.textContent=siblings.length>1?`같은 도감 번호로 등록된 기본·폼·메가 모습이 ${siblings.length.toLocaleString('ko-KR')}종 있습니다. 아래에서 다른 모습으로 바로 전환할 수 있습니다.`:'이 도감 번호에는 별도로 등록된 모습이 없습니다.'}else{const isMove=kind==='moves';detailPokemonExtra.hidden=true;detailPokemonExtra.innerHTML='';detailFormsSection.hidden=true;detailForms.innerHTML='';detailType.textContent=`${isMove?'기술':'특성'} · ${isMove?'MOVE':'ABILITY'} #${String(x.id).padStart(4,'0')}`;detailTitle.textContent=x.ko;detailShortLabel.textContent='요약 설명';detailShort.textContent=x.desc||'요약 설명이 없습니다.';detailLongLabel.textContent='상세 설명';detailLong.textContent=x.long||x.desc||'상세 설명이 없습니다.'}backdrop.hidden=false;document.body.classList.add('modal-open');if(!keepFocus)detailClose.focus()}
function closeDetail(){if(backdrop.hidden)return;backdrop.hidden=true;document.body.classList.remove('modal-open')}
const loadedScripts=new Set();
function loadScript(src){if(loadedScripts.has(src))return Promise.resolve();return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=`${src}?v=20261009-stage13-lazy`;s.async=false;s.onload=()=>{loadedScripts.add(src);resolve()};s.onerror=()=>reject(new Error(`load failed: ${src}`));document.body.appendChild(s)})}
function buildMoves(){const raw=Array.isArray(window.ER_MOVES)?window.ER_MOVES:[],short=new Map((Array.isArray(window.ER_MOVE_SHORT_KO)?window.ER_MOVE_SHORT_KO:[]).map(r=>[Number(r[0]),String(r[1]||'')])),long=new Map((Array.isArray(window.ER_MOVE_LONG_KO)?window.ER_MOVE_LONG_KO:[]).map(r=>[Number(r[0]),String(r[1]||'')]));moves=raw.filter(r=>Array.isArray(r)&&Number(r[0])>0&&String(r[1]||'').trim()&&String(r[1]||'').trim()!=="'-").map(r=>({id:Number(r[0]),ko:String(r[1]||''),desc:short.get(Number(r[0]))||'',long:long.get(Number(r[0]))||''}));dataReady.moves=true}
function buildAbilities(){const raw=Array.isArray(window.ER_ABILITIES)?window.ER_ABILITIES:[],short=new Map((Array.isArray(window.ER_ABILITY_SHORT_KO)?window.ER_ABILITY_SHORT_KO:[]).map(r=>[Number(r[0]),String(r[1]||'')])),long=new Map((Array.isArray(window.ER_ABILITY_LONG_KO)?window.ER_ABILITY_LONG_KO:[]).map(r=>[Number(r[0]),String(r[1]||'')]));abilities=raw.filter(r=>Array.isArray(r)&&Number(r[0])>0&&String(r[1]||'').trim()).map(r=>({id:Number(r[0]),ko:String(r[1]||''),desc:short.get(Number(r[0]))||'',long:long.get(Number(r[0]))||''}));dataReady.abilities=true}
async function ensureData(kind){if(kind==='pokemon'||dataReady[kind])return;if(dataLoading[kind])return dataLoading[kind];const files=kind==='moves'?['moves-1.js','moves-2.js','moves-3.js','move-short-1.js','move-short-2.js','move-short-3.js','move-short-4.js','move-long-1.js','move-long-2.js','move-long-3.js','move-long-4.js']:['abilities-1.js','abilities-2.js','abilities-3.js','ability-short-1.js','ability-short-2.js','ability-short-3.js','ability-short-4.js','ability-long-1.js','ability-long-2a.js','ability-long-2b.js','ability-long-3a.js','ability-long-3b.js','ability-long-4.js','ability-stage18.js'];dataLoading[kind]=(async()=>{for(const f of files)await loadScript(f);kind==='moves'?buildMoves():buildAbilities()})();try{await dataLoading[kind]}finally{dataLoading[kind]=null}}
function showLoading(kind){const m=kind==='moves'?['기술 도감','기술 데이터']:['특성 도감','특성 데이터'];filters.hidden=true;title.textContent=m[0];count.textContent='…';countLabel.textContent=m[1]+' 불러오는 중';result.textContent='';grid.classList.add('moves');grid.classList.remove('pokemon-grid');grid.innerHTML='<div class="data-loading">필요한 데이터만 불러오는 중입니다.</div>';loadWrap.hidden=true;empty.hidden=true}
async function switchView(next,btn){const generation=++tabGeneration;view=next;tabs.forEach(x=>x.classList.toggle('active',x===btn));q.value='';closeDetail();if(next!=='pokemon'&&!dataReady[next]){showLoading(next);try{await ensureData(next)}catch(e){if(generation===tabGeneration){grid.innerHTML='<div class="data-loading">데이터를 불러오지 못했습니다. 다시 눌러주세요.</div>';count.textContent='0'}return}}if(generation!==tabGeneration)return;loadWrap.hidden=false;render();window.scrollTo({top:0,behavior:'smooth'})}
q.addEventListener('input',render);
tabs.forEach(btn=>btn.addEventListener('click',()=>switchView(btn.dataset.view||'pokemon',btn)));
if(categoryFilters)categoryFilters.addEventListener('click',e=>{const btn=e.target.closest('[data-category]');if(!btn)return;const k=btn.dataset.category;if(activeCategories.has(k))activeCategories.delete(k);else activeCategories.add(k);renderCategoryFilters();render()});
if(typeFilters)typeFilters.addEventListener('click',e=>{const btn=e.target.closest('.type-filter');if(!btn)return;const t=btn.dataset.type;if(activeTypes.has(t))activeTypes.delete(t);else activeTypes.add(t);renderTypeFilters();render()});
if(resetFilters)resetFilters.addEventListener('click',()=>{activeCategories.clear();['base','form','mega'].forEach(k=>activeCategories.add(k));activeTypes.clear();renderCategoryFilters();renderTypeFilters();if(sortPokemon)sortPokemon.value='dex';q.value='';render()});
if(sortPokemon)sortPokemon.addEventListener('change',render);loadMore.addEventListener('click',appendNext);
grid.addEventListener('click',e=>{const card=e.target.closest('.is-detail');if(card)openDetail(card.dataset.kind,Number(card.dataset.id))});
grid.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest('.is-detail')){e.preventDefault();const card=e.target.closest('.is-detail');openDetail(card.dataset.kind,Number(card.dataset.id))}});
grid.addEventListener('error',e=>{if(e.target?.classList?.contains('sprite')){e.target.hidden=true;e.target.closest('.sprite-wrap')?.classList.add('no-image')}},true);
detailPokemonExtra?.addEventListener('error',e=>{if(e.target?.classList?.contains('detail-sprite')){e.target.hidden=true;e.target.closest('.detail-sprite-wrap')?.classList.add('no-image')}},true);
detailForms.addEventListener('click',e=>{const btn=e.target.closest('.form-link');if(btn)openDetail('pokemon',Number(btn.dataset.id),true)});
detailClose.addEventListener('click',closeDetail);backdrop.addEventListener('click',e=>{if(e.target===backdrop)closeDetail()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!backdrop.hidden){closeDetail();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();q.focus();q.select()}});
renderCategoryFilters();renderTypeFilters();render();
window.ER_STAGE13_META={stage:13,categories:{base:species.filter(x=>x.category==='base').length,form:species.filter(x=>x.category==='form').length,mega:species.filter(x=>x.category==='mega').length},typeCount:new Set(species.flatMap(x=>x.types)).size,pageSize:PAGE_SIZE.pokemon};
})();
