(()=>{'use strict';
const speciesByEn={};
for(const r of (window.ER_SPECIES||[])){if(r&&r.length>=3)speciesByEn[String(r[1])]={id:+r[0],en:String(r[1]),ko:String(r[2])};}
const movesById={};for(const r of (window.ER_MOVES||[])){if(r&&+r[0]!==0)movesById[String(+r[0])]={id:+r[0],ko:String(r[r.length-1]||'')};}
const abilitiesById={};for(const r of (window.ER_ABILITIES||[])){if(r&&+r[0]!==0)abilitiesById[String(+r[0])]={id:+r[0],ko:String(r[r.length-1]||'')};}
const K={speciesByEn,movesById,abilitiesById};
const OFFICIAL=['https://cdn.jsdelivr.net/gh/ForwardFeed/ER-nextdex@main/static/js/data/gameDataV2.65beta.json','https://raw.githubusercontent.com/ForwardFeed/ER-nextdex/main/static/js/data/gameDataV2.65beta.json'];
const TYPE_KO=['노말','격투','불꽃','얼음','전기','벌레','비행','강철','풀','땅','독','악','물','에스퍼','바위','드래곤','고스트','페어리','스텔라'];
const TYPE_COLOR=['#9fa19f','#ff8000','#e62829','#3dcef3','#fac000','#91a119','#81b9ef','#60a1b8','#3fa129','#915121','#9141cb','#50413f','#2980ef','#ef4179','#afa981','#5060e1','#704170','#ef70ef','#40b5a5'];
const STAT_KO=['HP','공격','방어','특공','특방','스피드'];
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)];
const state={data:null,sp:[],mv:[],ab:[],species:[],moves:[],normal:[],innates:[],owner:new Map(),view:'pokemon',group:'original',q:'',type:null,sort:'id',limit:160};
const FORM={ALOLAN:'알로라의 모습',ALOLA:'알로라의 모습',GALARIAN:'가라르의 모습',GALAR:'가라르의 모습',HISUIAN:'히스이의 모습',HISUI:'히스이의 모습',PALDEAN:'팔데아의 모습',PALDEA:'팔데아의 모습',ORIGIN:'오리진폼',THERIAN:'영물폼',INCARNATE:'화신폼',ATTACK:'어택폼',DEFENSE:'디펜스폼',SPEED:'스피드폼',SANDY:'모래땅도롱',TRASH:'슈레도롱',PLANT:'초목도롱',EAST:'동쪽바다',WEST:'서쪽바다',HEAT:'히트로토무',WASH:'워시로토무',FROST:'프로스트로토무',FAN:'스핀로토무',MOW:'커트로토무',BLACK:'블랙큐레무',WHITE:'화이트큐레무',BLADE:'블레이드폼',SHIELD:'실드폼',ASH:'지우폼',COMPLETE:'퍼펙트폼',MIDDAY:'한낮의 모습',MIDNIGHT:'한밤중의 모습',DUSK:'황혼의 모습',SCHOOL:'군집의 모습',SOLO:'단독의 모습',METEOR:'유성의 모습',CORE:'코어의 모습',DUSK_MANE:'황혼의 갈기',DAWN_WINGS:'새벽의 날개',ULTRA:'울트라폼',AMPED:'하이한 모습',LOW_KEY:'로우한 모습',HANGRY:'배고픈 모습',CROWNED_SWORD:'검왕의 모습',CROWNED_SHIELD:'방패왕의 모습',ETERNAMAX:'무한다이맥스',SINGLE_STRIKE:'일격의 태세',RAPID_STRIKE:'연격의 태세',ICE_RIDER:'백마 탄 모습',SHADOW_RIDER:'흑마 탄 모습',HERO:'마이티폼',ZERO:'나이브폼',CURLY:'늘어진 모습',DROOPY:'처진 모습',STRETCHY:'뻗은 모습',TWO_SEGMENT:'두 마디폼',THREE_SEGMENT:'세 마디폼',CHEST:'상자폼',ROAMING:'도보폼',TEAL_MASK:'벽록의 가면',HEARTHFLAME_MASK:'화덕의 가면',WELLSPRING_MASK:'우물의 가면',CORNERSTONE_MASK:'주춧돌의 가면',TERASTAL:'테라스탈폼',STELLAR:'스텔라폼',BLOODMOON:'붉은 달의 모습'};
const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
const norm=v=>String(v??'').toLowerCase().replace(/[\s·._'’\-–—():%]/g,'');
const atSp=i=>state.sp[+i]||null,atMv=i=>state.mv[+i]||null,atAb=i=>state.ab[+i]||null;
const bst=m=>(m?.stats?.base||[]).reduce((a,b)=>a+(+b||0),0);
const split=v=>({0:'물리',1:'특수',2:'변화',3:'혼합',4:'특수분류'})[v]||`분류 ${v}`;
const badge=t=>`<span class="badge" style="background:${TYPE_COLOR[t]||'#666'}">${esc(TYPE_KO[t]||'타입 '+t)}</span>`;
const sprite=m=>`https://cdn.jsdelivr.net/gh/ForwardFeed/ER-nextdex@main/static/sprites/${encodeURIComponent(String(m?.NAME||'').replace(/^SPECIES_/,''))}.png`;
function rootIndex(i){let c=+i,seen=new Set();while(state.owner.has(c)&&!seen.has(c)){seen.add(c);c=state.owner.get(c)}return c}
function rootSpecies(m){return atSp(rootIndex(m.__idx))||m}
function speciesLocal(m){const direct=K.speciesByEn?.[m?.name]||Object.entries(K.speciesByEn||{}).find(([en])=>norm(en)===norm(m?.name))?.[1];if(direct)return direct;const r=rootSpecies(m);return K.speciesByEn?.[r.name]||Object.entries(K.speciesByEn||{}).find(([en])=>norm(en)===norm(r.name))?.[1]||null}
function formToken(m){const r=rootSpecies(m);if(!r||r.__idx===m.__idx)return'';const a=String(r.NAME||'').replace(/^SPECIES_/,''),b=String(m.NAME||'').replace(/^SPECIES_/,'');if(a&&b.startsWith(a+'_'))return b.slice(a.length+1);const rn=String(r.name||''),mn=String(m.name||'');if(rn&&mn.toLowerCase().includes(rn.toLowerCase()))return mn.replace(new RegExp(rn.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'),'').replace(/^[_\s-]+/,'').replace(/[\s-]+/g,'_').toUpperCase();return b}
function koSpecies(m){const direct=K.speciesByEn?.[m?.name]||Object.entries(K.speciesByEn||{}).find(([en])=>norm(en)===norm(m?.name))?.[1];if(direct)return direct.ko;const l=speciesLocal(m);if(!l)return m.name||'포켓몬';const t=formToken(m);if(!t)return l.ko;if(t==='MEGA')return '메가'+l.ko;if(t==='MEGA_X')return '메가'+l.ko+'X';if(t==='MEGA_Y')return '메가'+l.ko+'Y';if(t==='PRIMAL')return '원시'+l.ko;let f=FORM[t]||FORM[t.replace(/_FORM(E)?$/,'')];if(f)return `${l.ko} (${f})`;if(/REDUX/i.test(t))return `${l.ko} (리덕스폼)`;return `${l.ko} (특수폼)`}
function groupOf(m){const code=String(m?.NAME||''),name=String(m?.name||'');if(/(?:^|_)REDUX(?:_|$)/i.test(code)||/\bRedux\b/i.test(name))return'redux';const id=Number(m?.id??m?.__idx);return Number.isFinite(id)&&id>1025?'redux':'original'}
const groupLabel=m=>groupOf(m)==='redux'?'리덕스 추가':'오리지널';
function localMove(m){if(!m)return{ko:'',en:'',desc:''};const x=K.movesById?.[String(m.id)];return x?{...x,en:m.name||'',desc:''}:{en:m.name||'',ko:m.name||`기술 ${m.id??'?'}`,desc:''}}
function localAbility(a){if(!a)return{ko:'',en:'',desc:''};const x=K.abilitiesById?.[String(a.id)];return x?{...x,en:a.name||'',desc:''}:{en:a.name||'',ko:a.name||`특성 ${a.id??'?'}`,desc:''}}
function fullDesc(local,official){return String(local?.desc||official||'').trim()}
function shortDesc(s){s=String(s||'').trim();if(!s)return'';const first=s.split(/\n+/).map(x=>x.trim()).find(Boolean)||s;return first.length>74?first.slice(0,73).trim()+'…':first}
function descToggle(full){full=String(full||'').trim();if(!full)return'<div class="desc-plain">설명이 없습니다.</div>';const sh=shortDesc(full);if(sh===full.replace(/\n+/g,' ').trim())return`<div class="desc-plain">${esc(full)}</div>`;return`<details class="desc-toggle"><summary><span>${esc(sh)}</span><em>자세히</em></summary><div class="desc-full">${esc(full)}</div></details>`}
async function load(){for(const u of OFFICIAL){try{const r=await fetch(u,{cache:'force-cache'});if(r.ok)return await r.json()}catch(e){console.warn(e)}}throw Error('공식 데이터 연결 실패')}
function prepare(d){state.data=d;state.sp=(d.species||[]).map((x,i)=>x?Object.assign({},x,{__idx:i}):null);state.mv=(d.moves||[]).map((x,i)=>x?Object.assign({},x,{__idx:i}):null);state.ab=(d.abilities||[]).map((x,i)=>x?Object.assign({},x,{__idx:i}):null);state.owner.clear();state.sp.forEach((m,i)=>{if(!m)return;(m.forms||[]).forEach(v=>{v=+v;if(Number.isInteger(v)&&v>=0&&v!==i&&!state.owner.has(v))state.owner.set(v,i)})});state.species=state.sp.filter(x=>x&&x.id!==-1&&x.name);state.moves=state.mv.filter(x=>x&&Number(x.id)!==0&&x.name);const normal=new Set(),innate=new Set();state.species.forEach(m=>{(m.stats?.abis||[]).forEach(v=>{v=+v;const a=atAb(v);if(a&&Number(a.id)!==0)normal.add(v)});(m.stats?.inns||[]).forEach(v=>{v=+v;const a=atAb(v);if(a&&Number(a.id)!==0)innate.add(v)})});state.normal=[...normal].map(atAb).filter(a=>a&&Number(a.id)!==0);state.innates=[...innate].map(atAb).filter(a=>a&&Number(a.id)!==0);renderCounts()}
function renderCounts(){const o=state.species.filter(x=>groupOf(x)==='original').length,r=state.species.length-o;$('#counts').innerHTML=[['오리지널',o],['리덕스 추가',r],['기술',state.moves.length],['고유 특성',state.innates.length]].map(([k,v])=>`<div class="count"><b>${v.toLocaleString()}</b><span>${k}</span></div>`).join('')}
function listForView(){return state.view==='pokemon'?state.species:state.view==='moves'?state.moves:state.view==='abilities'?state.normal:state.innates}
function searchText(x){if(state.view==='pokemon')return `${koSpecies(x)} ${x.name||''} ${x.NAME||''}`;if(state.view==='moves'){const l=localMove(x);return `${l.ko} ${x.name||''} ${x.desc||''} ${x.lDesc||''}`}const l=localAbility(x);return `${l.ko} ${x.name||''} ${x.desc||''}`}
function filtered(){let a=[...listForView()];if(state.view==='pokemon')a=a.filter(x=>groupOf(x)===state.group);if(state.q){const q=norm(state.q);a=a.filter(x=>norm(searchText(x)).includes(q))}if(state.type!==null){if(state.view==='pokemon')a=a.filter(x=>(x.stats?.types||[]).includes(state.type));if(state.view==='moves')a=a.filter(x=>(x.types||[]).includes(state.type))}if(state.view==='pokemon')a.sort((x,y)=>state.sort==='name'?koSpecies(x).localeCompare(koSpecies(y),'ko'):state.sort==='bst'?bst(y)-bst(x):(x.id??99999)-(y.id??99999));else if(state.sort==='name')a.sort((x,y)=>searchText(x).localeCompare(searchText(y),'ko'));else a.sort((x,y)=>(x.id??99999)-(y.id??99999));return a}
function renderFilters(){const g=$('#groups');g.classList.toggle('hidden',state.view!=='pokemon');g.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.group===state.group));const e=$('#types');if(!['pokemon','moves'].includes(state.view)){e.innerHTML='';e.classList.add('hidden');return}e.classList.remove('hidden');e.innerHTML=`<button class="type-filter ${state.type===null?'active':''}" data-t="">전체</button>`+TYPE_KO.slice(0,18).map((t,i)=>`<button class="type-filter ${state.type===i?'active':''}" data-t="${i}">${t}</button>`).join('');e.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.type=b.dataset.t===''?null:+b.dataset.t;render()})}
function monCard(m){return`<article class="card mon" data-kind="pokemon" data-ref="${m.__idx}"><div class="spritebox"><img class="sprite" loading="lazy" src="${sprite(m)}" onerror="this.style.opacity=.12"></div><div><div class="card-top"><span class="num">#${m.id??'?'}</span><span class="origin ${groupOf(m)}">${groupLabel(m)}</span></div><h3>${esc(koSpecies(m))}</h3><div class="en">${esc(m.name)}</div><div class="badges">${[...new Set(m.stats?.types||[])].map(badge).join('')}</div><div class="en">BST ${bst(m)}</div></div></article>`}
function moveCard(m){const l=localMove(m),desc=fullDesc(l,m.lDesc||m.desc);return`<article class="card" data-kind="move" data-ref="${m.__idx}"><span class="num">#${m.id}</span><h3>${esc(l.ko)}</h3><div class="en">${esc(m.name)}</div><div class="badges">${(m.types||[]).map(badge).join('')}<span class="pill">${esc(split(m.split))}</span><span class="pill">위력 ${m.pwr||'—'}</span></div>${descToggle(desc)}</article>`}
function abilityCard(a,isUnique){const l=localAbility(a),desc=fullDesc(l,a.desc);return`<article class="card" data-kind="ability" data-ref="${a.__idx}"><div class="card-top"><span class="num">#${a.id}</span>${isUnique?'<span class="unique-label">고유 특성</span>':''}</div><h3>${esc(l.ko)}</h3><div class="en">${esc(a.name)}</div>${descToggle(desc)}</article>`}
function render(){$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));const labels={pokemon:['포켓몬','종족값 · 타입 · 특성 · 고유 특성 · 진화 · 폼'],moves:['기술','짧은 설명을 누르면 전체 설명 표시'],abilities:['특성','일반 특성 · 짧은/전체 설명 · 보유 포켓몬'],innates:['고유 특성','고유 특성 · 짧은/전체 설명 · 보유 포켓몬']}[state.view];$('#title').textContent=labels[0];$('#sort').style.display=['abilities','innates'].includes(state.view)?'none':'block';renderFilters();const all=filtered(),shown=all.slice(0,state.limit);$('#sub').textContent=`${labels[1]} · ${all.length.toLocaleString()}개`;$('#grid').className='grid '+(state.view==='pokemon'?'':'text');$('#grid').innerHTML=state.view==='pokemon'?shown.map(monCard).join(''):state.view==='moves'?shown.map(moveCard).join(''):shown.map(x=>abilityCard(x,state.view==='innates')).join('');$('#empty').classList.toggle('hidden',all.length>0);$('#more').classList.toggle('hidden',all.length<=state.limit);bindCards();$('#grid').querySelectorAll('details').forEach(d=>d.onclick=e=>e.stopPropagation())}
function abilityBox(ref,isUnique){const a=atAb(+ref);if(!a||Number(a.id)===0)return'';const l=localAbility(a);return`<button class="ability-box ${isUnique?'unique':''}" data-aref="${a.__idx}"><b>${esc(l.ko)}</b><small>${isUnique?'고유 특성 · ':''}${esc(a.name)}</small></button>`}
function evoText(e){let k=String(state.data?.evoKindT?.[e.kd]||'').toUpperCase(),s=String(e.rs??'').replace(/^ITEM_/,'').replace(/^MOVE_/,'').replace(/_/g,' ');if(k.includes('LEVEL'))return s?`레벨 ${s}`:'레벨업';if(k.includes('ITEM'))return s?`${s} 사용`:'도구 사용';if(k.includes('FRIEND'))return'친밀도';if(k.includes('TRADE'))return'통신교환';if(k.includes('MOVE'))return s?`${s} 습득`:'특정 기술 습득';if(k.includes('MAP')||k.includes('LOCATION'))return'특정 장소';if(k.includes('TIME'))return'특정 시간대';return s||'진화 조건'}
function evolutionCards(m){return(m.evolutions||[]).map(e=>{const t=atSp(+e.in);return t?`<button class="relation-card" data-pref="${t.__idx}"><span>${esc(evoText(e))}</span><b>${esc(koSpecies(t))}</b><small>${esc(t.name)}</small></button>`:''}).join('')}
function formCards(m){const root=rootSpecies(m);const ids=[...(root.forms||[])].map(Number);if(root.__idx!==m.__idx)ids.unshift(root.__idx);const seen=new Set();return ids.filter(i=>Number.isInteger(i)&&!seen.has(i)&&seen.add(i)&&i!==m.__idx).map(i=>{const t=atSp(i);if(!t)return'';return`<button class="relation-card form" data-pref="${t.__idx}"><span>${groupOf(t)==='redux'?'리덕스 추가 폼':'폼'}</span><b>${esc(koSpecies(t))}</b><small>${esc(t.name)}</small></button>`}).join('')}
function monDetail(m){const types=[...new Set(m.stats?.types||[])],abs=(m.stats?.abis||[]).filter(i=>atAb(+i)&&Number(atAb(+i).id)!==0),inn=(m.stats?.inns||[]).filter(i=>atAb(+i)&&Number(atAb(+i).id)!==0),ev=evolutionCards(m),fm=formCards(m);const lv=(m.levelUpMoves||[]).map(x=>{const z=atMv(+x.id);return z&&Number(z.id)!==0?`<tr data-mref="${z.__idx}"><td>${x.lv}</td><td>${esc(localMove(z).ko)}</td><td>${esc(z.name)}</td></tr>`:''}).join('');return`<div class="detail"><div class="detail-head"><img class="detail-sprite" src="${sprite(m)}"><div><div class="card-top"><span class="num">#${m.id??'?'}</span><span class="origin ${groupOf(m)}">${groupLabel(m)}</span></div><h1>${esc(koSpecies(m))}</h1><div class="sub">${esc(m.name)}</div><div class="badges">${types.map(badge).join('')}</div></div></div><section class="section"><h2>종족값 · BST ${bst(m)}</h2><div class="stats">${(m.stats?.base||[]).map((v,i)=>`<div class="stat"><span>${STAT_KO[i]}</span><b>${v}</b><div class="bar"><i style="width:${Math.min(100,v/2)}%"></i></div></div>`).join('')}</div></section>${abs.length?`<section class="section"><h2>특성</h2><div class="ability-grid">${abs.map(x=>abilityBox(x,false)).join('')}</div></section>`:''}${inn.length?`<section class="section"><h2>고유 특성</h2><div class="ability-grid">${inn.map(x=>abilityBox(x,true)).join('')}</div></section>`:''}${ev?`<section class="section"><div class="relation-head"><h2>진화</h2></div><div class="relations">${ev}</div></section>`:''}${fm?`<section class="section"><div class="relation-head"><h2>폼</h2><span class="redux-note">리덕스 전용 폼은 ‘리덕스 추가’로 분류</span></div><div class="relations">${fm}</div></section>`:''}${lv?`<section class="section"><h2>레벨업 기술</h2><div class="tablewrap"><table class="table"><thead><tr><th>Lv.</th><th>한국어</th><th>English</th></tr></thead><tbody>${lv}</tbody></table></div></section>`:''}<div class="source">게임 수치와 연결 구조는 공식 NextDex v2.65beta 기준입니다.</div></div>`}
function moveDetail(m){const l=localMove(m),desc=fullDesc(l,m.lDesc||m.desc),idx=m.__idx;const holders=state.species.filter(p=>(p.levelUpMoves||[]).some(x=>+x.id===idx)||(p.tutor||[]).some(x=>+x===idx)||(p.TMHMMoves||[]).some(x=>+x===idx)||(p.eggMoves||[]).some(x=>+x===idx)).slice(0,180);return`<div class="detail"><span class="num">MOVE #${m.id}</span><h1>${esc(l.ko)}</h1><div class="sub">${esc(m.name)}</div><div class="badges">${(m.types||[]).map(badge).join('')}<span class="pill">${split(m.split)}</span><span class="pill">위력 ${m.pwr||'—'}</span><span class="pill">명중 ${m.acc||'—'}</span><span class="pill">PP ${m.pp??'—'}</span></div><section class="section"><h2>설명</h2><div class="desc-full">${esc(desc)}</div></section><section class="section"><h2>습득 포켓몬</h2><div class="tags">${holders.map(p=>`<button class="tag" data-pref="${p.__idx}">${esc(koSpecies(p))}</button>`).join('')}</div></section><div class="source">수치와 습득 구조는 공식 NextDex v2.65beta 기준입니다.</div></div>`}
function abilityDetail(a){const l=localAbility(a),desc=fullDesc(l,a.desc),idx=a.__idx,n=state.species.filter(p=>(p.stats?.abis||[]).some(x=>+x===idx)),u=state.species.filter(p=>(p.stats?.inns||[]).some(x=>+x===idx));return`<div class="detail"><span class="num">ABILITY #${a.id}</span><h1>${esc(l.ko)}</h1><div class="sub">${esc(a.name)}</div><section class="section"><h2>설명</h2><div class="desc-full">${esc(desc)}</div></section>${n.length?`<section class="section"><h2>특성으로 보유</h2><div class="tags">${n.map(p=>`<button class="tag" data-pref="${p.__idx}">${esc(koSpecies(p))}</button>`).join('')}</div></section>`:''}${u.length?`<section class="section"><h2>고유 특성으로 보유</h2><div class="tags">${u.map(p=>`<button class="tag" data-pref="${p.__idx}">${esc(koSpecies(p))}</button>`).join('')}</div></section>`:''}<div class="source">보유 관계는 공식 NextDex v2.65beta 기준입니다.</div></div>`}
function openKind(kind,ref){let x,html='';if(kind==='pokemon'&&(x=atSp(+ref)))html=monDetail(x);if(kind==='move'&&(x=atMv(+ref))&&Number(x.id)!==0)html=moveDetail(x);if(kind==='ability'&&(x=atAb(+ref))&&Number(x.id)!==0)html=abilityDetail(x);if(!html)return;$('#detail').innerHTML=html;$('#backdrop').classList.remove('hidden');document.body.style.overflow='hidden';$('#detail').querySelectorAll('[data-pref]').forEach(b=>b.onclick=()=>openKind('pokemon',+b.dataset.pref));$('#detail').querySelectorAll('[data-mref]').forEach(b=>b.onclick=()=>openKind('move',+b.dataset.mref));$('#detail').querySelectorAll('[data-aref]').forEach(b=>b.onclick=()=>openKind('ability',+b.dataset.aref))}
function close(){$('#backdrop').classList.add('hidden');document.body.style.overflow=''}
function bindCards(){$('#grid').querySelectorAll('[data-kind]').forEach(c=>c.onclick=()=>openKind(c.dataset.kind,+c.dataset.ref))}
function bind(){$$('.tab').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;state.type=null;state.sort='id';state.limit=160;$('#sort').value='id';render();window.scrollTo({top:0,behavior:'smooth'})});$('#groups').querySelectorAll('button').forEach(b=>b.onclick=()=>{state.group=b.dataset.group;state.limit=160;render()});$('#q').oninput=e=>{state.q=e.target.value;state.limit=160;render()};$('#sort').onchange=e=>{state.sort=e.target.value;render()};$('#more').onclick=()=>{state.limit+=160;render()};$('#close').onclick=close;$('#backdrop').onclick=e=>{if(e.target===$('#backdrop'))close()};$('#theme').onclick=()=>{document.documentElement.classList.toggle('light');localStorage.setItem('erdex-theme',document.documentElement.classList.contains('light')?'light':'dark')};$('#brand').onclick=()=>{state.view='pokemon';state.group='original';state.q='';state.type=null;$('#q').value='';render();window.scrollTo({top:0,behavior:'smooth'})};document.addEventListener('keydown',e=>{if(e.key==='Escape')close()})}
(async()=>{try{if(localStorage.getItem('erdex-theme')==='light')document.documentElement.classList.add('light')}catch(e){}bind();try{const d=await load();prepare(d);render();$('#status').textContent=`공식 NextDex v2.65beta 연결 완료 · 포켓몬/폼 ${state.species.length.toLocaleString()}개`}catch(e){console.error(e);$('#status').textContent='공식 NextDex 데이터 연결 실패 · 네트워크 연결을 확인해 주세요';$('#empty').classList.remove('hidden')}})();
})();