(()=>{'use strict';
const $=q=>document.querySelector(q),$$=q=>[...document.querySelectorAll(q)],norm=s=>String(s||'').toLowerCase().replace(/[\s·._'’\-–—():%]/g,''),esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]||c));
const OFFICIAL=['https://cdn.jsdelivr.net/gh/ForwardFeed/ER-nextdex@main/static/js/data/gameDataV2.65beta.json','https://raw.githubusercontent.com/ForwardFeed/ER-nextdex/main/static/js/data/gameDataV2.65beta.json'];
const TK=['노말','격투','불꽃','얼음','전기','벌레','비행','강철','풀','땅','독','악','물','에스퍼','바위','드래곤','고스트','페어리','스텔라'],TC=['#9fa19f','#ff8000','#e62829','#3dcef3','#fac000','#91a119','#81b9ef','#60a1b8','#3fa129','#915121','#9141cb','#50413f','#2980ef','#ef4179','#afa981','#5060e1','#704170','#ef70ef','#40b5a5'],SK=['HP','공격','방어','특공','특방','스피드'];
const speciesRows=window.ER_SPECIES||[],moveRows=window.ER_MOVES||[],abilityRows=window.ER_ABILITIES||[];
const spExact=new Map(),spNorm=new Map();for(const r of speciesRows){if(!r||r.length<3)continue;const o={id:+r[0],en:String(r[1]),ko:String(r[2])};spExact.set(o.en,o);const k=norm(o.en);if(!spNorm.has(k))spNorm.set(k,o);else spNorm.set(k,null);}const moveKo=new Map(moveRows.map(r=>[+r[0],String(r[r.length-1]||'')])),abilityKo=new Map(abilityRows.map(r=>[+r[0],String(r[r.length-1]||'')]));
const FORM={ALOLAN:'알로라의 모습',ALOLA:'알로라의 모습',GALARIAN:'가라르의 모습',GALAR:'가라르의 모습',HISUIAN:'히스이의 모습',HISUI:'히스이의 모습',PALDEAN:'팔데아의 모습',PALDEA:'팔데아의 모습',ORIGIN:'오리진폼',THERIAN:'영물폼',INCARNATE:'화신폼',ATTACK:'어택폼',DEFENSE:'디펜스폼',SPEED:'스피드폼',SANDY:'모래땅도롱',TRASH:'슈레도롱',PLANT:'초목도롱',EAST:'동쪽바다',WEST:'서쪽바다',HEAT:'히트로토무',WASH:'워시로토무',FROST:'프로스트로토무',FAN:'스핀로토무',MOW:'커트로토무',BLACK:'블랙큐레무',WHITE:'화이트큐레무',BLADE:'블레이드폼',SHIELD:'실드폼',ASH:'지우폼',COMPLETE:'퍼펙트폼',MIDDAY:'한낮의 모습',MIDNIGHT:'한밤중의 모습',DUSK:'황혼의 모습',SCHOOL:'군집의 모습',SOLO:'단독의 모습',METEOR:'유성의 모습',CORE:'코어의 모습',DUSK_MANE:'황혼의 갈기',DAWN_WINGS:'새벽의 날개',ULTRA:'울트라폼',AMPED:'하이한 모습',LOW_KEY:'로우한 모습',HANGRY:'배고픈 모습',CROWNED_SWORD:'검왕의 모습',CROWNED_SHIELD:'방패왕의 모습',ETERNAMAX:'무한다이맥스',SINGLE_STRIKE:'일격의 태세',RAPID_STRIKE:'연격의 태세',ICE_RIDER:'백마 탄 모습',SHADOW_RIDER:'흑마 탄 모습',HERO:'마이티폼',ZERO:'나이브폼',CURLY:'늘어진 모습',DROOPY:'처진 모습',STRETCHY:'뻗은 모습',TWO_SEGMENT:'두 마디폼',THREE_SEGMENT:'세 마디폼',CHEST:'상자폼',ROAMING:'도보폼',TEAL_MASK:'벽록의 가면',HEARTHFLAME_MASK:'화덕의 가면',WELLSPRING_MASK:'우물의 가면',CORNERSTONE_MASK:'주춧돌의 가면',TERASTAL:'테라스탈폼',STELLAR:'스텔라폼',BLOODMOON:'붉은 달의 모습'};
const S={d:null,sp:[],mv:[],ab:[],listSp:[],listMv:[],normal:[],unique:[],owner:new Map(),view:'pokemon',group:'original',q:'',type:null,sort:'id',limit:160,cut:1025};
const atSp=i=>S.sp[+i]||null,atMv=i=>S.mv[+i]||null,atAb=i=>S.ab[+i]||null,badge=t=>`<span class="badge" style="background:${TC[t]||'#666'}">${esc(TK[t]||'타입 '+t)}</span>`,bst=m=>(m.stats?.base||[]).reduce((a,b)=>a+(+b||0),0),sprite=m=>`https://cdn.jsdelivr.net/gh/ForwardFeed/ER-nextdex@main/static/sprites/${encodeURIComponent(String(m.NAME||'').replace(/^SPECIES_/,''))}.png`;
function root(i){let c=+i,z=new Set();while(S.owner.has(c)&&!z.has(c)){z.add(c);c=S.owner.get(c)}return c}
function baseLocal(m){const r=atSp(root(m.__i))||m;return spExact.get(r.name)||spNorm.get(norm(r.name))||null}
function token(m){const r=atSp(root(m.__i));if(!r||r.__i===m.__i)return'';let a=String(r.NAME||'').replace(/^SPECIES_/,''),b=String(m.NAME||'').replace(/^SPECIES_/,'');if(a&&b.startsWith(a+'_'))return b.slice(a.length+1);let rn=String(r.name||''),mn=String(m.name||'');if(rn&&mn.toLowerCase().includes(rn.toLowerCase()))return mn.replace(new RegExp(rn.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'),'').replace(/^[_\s-]+/,'').replace(/[\s-]+/g,'_').toUpperCase();return b}
function koName(m){const l=baseLocal(m);if(!l)return m.name||'포켓몬';const t=token(m);if(!t)return l.ko;if(t==='MEGA')return '메가'+l.ko;if(t==='MEGA_X')return '메가'+l.ko+'X';if(t==='MEGA_Y')return '메가'+l.ko+'Y';if(t==='PRIMAL')return '원시'+l.ko;let f=FORM[t]||FORM[t.replace(/_FORM(E)?$/,'')]||'';return f?`${l.ko} (${f})`:`${l.ko} (특수폼)`}
function grp(m){const r=atSp(root(m.__i))||m,d=+r.dex?.id;return Number.isFinite(d)&&d>=0&&d<=S.cut?'original':'redux'}
function gko(m){return grp(m)==='original'?'오리지널':'리덕스 추가'}
function moveName(m){return moveKo.get(+m.id)||m.name||`기술 ${m.id}`}
function abilityName(a){return abilityKo.get(+a.id)||a.name||`특성 ${a.id}`}
function split(v){return({0:'물리',1:'특수',2:'변화',3:'혼합',4:'특수분류'})[v]||`분류 ${v}`}
async function load(){for(const u of OFFICIAL){try{const r=await fetch(u,{cache:'force-cache'});if(r.ok)return await r.json()}catch(e){console.warn(e)}}throw Error('공식 데이터 연결 실패')}
function prep(d){S.d=d;S.sp=(d.species||[]).map((x,i)=>x?Object.assign({},x,{__i:i}):null);S.mv=(d.moves||[]).map((x,i)=>x?Object.assign({},x,{__i:i}):null);S.ab=(d.abilities||[]).map((x,i)=>x?Object.assign({},x,{__i:i}):null);S.sp.forEach((m,i)=>m&&(m.forms||[]).forEach(x=>{x=+x;if(x>=0&&x!==i&&!S.owner.has(x))S.owner.set(x,i)}));S.listSp=S.sp.filter(x=>x&&x.id!==-1&&x.name);S.listMv=S.mv.filter(x=>x&&x.name);const n=new Set(),u=new Set();S.listSp.forEach(m=>{(m.stats?.abis||[]).forEach(x=>atAb(+x)&&n.add(+x));(m.stats?.inns||[]).forEach(x=>atAb(+x)&&u.add(+x))});S.normal=[...n].map(atAb).filter(Boolean);S.unique=[...u].map(atAb).filter(Boolean);const p=S.listSp.find(m=>norm(m.name)==='pecharunt'&&!S.owner.has(m.__i));if(p&&Number.isFinite(+p.dex?.id))S.cut=+p.dex.id;const o=S.listSp.filter(m=>grp(m)==='original').length,r=S.listSp.length-o;$('#counts').innerHTML=[['오리지널',o],['리덕스 추가',r],['기술',S.listMv.length],['고유 특성',S.unique.length]].map(x=>`<div class="count"><b>${x[1].toLocaleString()}</b><span>${x[0]}</span></div>`).join('')}
function searchText(x){if(S.view==='pokemon')return koName(x)+' '+x.name+' '+(x.NAME||'');if(S.view==='moves')return moveName(x)+' '+x.name;return abilityName(x)+' '+x.name}
function arr(){if(S.view==='pokemon')return S.listSp;if(S.view==='moves')return S.listMv;if(S.view==='abilities')return S.normal;return S.unique}
function filt(){let a=[...arr()];if(S.view==='pokemon')a=a.filter(x=>grp(x)===S.group);if(S.q){let q=norm(S.q);a=a.filter(x=>norm(searchText(x)).includes(q))}if(S.type!==null){if(S.view==='pokemon')a=a.filter(x=>(x.stats?.types||[]).includes(S.type));if(S.view==='moves')a=a.filter(x=>(x.types||[]).includes(S.type))}if(S.view==='pokemon')a.sort((x,y)=>S.sort==='name'?koName(x).localeCompare(koName(y),'ko'):S.sort==='bst'?bst(y)-bst(x):(x.dex?.id??x.id??99999)-(y.dex?.id??y.id??99999));else if(S.sort==='name')a.sort((x,y)=>searchText(x).localeCompare(searchText(y),'ko'));else a.sort((x,y)=>(x.id??99999)-(y.id??99999));return a}
function filters(){const g=$('#groups');g.classList.toggle('hidden',S.view!=='pokemon');g.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.group===S.group));const e=$('#types');if(!['pokemon','moves'].includes(S.view)){e.innerHTML='';e.classList.add('hidden');return}e.classList.remove('hidden');e.innerHTML=`<button class="type-filter ${S.type===null?'active':''}" data-t="">전체</button>`+TK.slice(0,18).map((t,i)=>`<button class="type-filter ${S.type===i?'active':''}" data-t="${i}">${t}</button>`).join('');e.querySelectorAll('button').forEach(b=>b.onclick=()=>{S.type=b.dataset.t===''?null:+b.dataset.t;render()})}
function monCard(m){return`<article class="card mon" data-k="p" data-i="${m.__i}"><div class="spritebox"><img class="sprite" loading="lazy" src="${sprite(m)}" onerror="this.style.opacity=.12"></div><div><div class="card-top"><span class="num">#${m.dex?.id??m.id}</span><span class="origin ${grp(m)}">${gko(m)}</span></div><h3>${esc(koName(m))}</h3><div class="en">${esc(m.name)}</div><div class="badges">${[...new Set(m.stats?.types||[])].map(badge).join('')}</div><div class="en">BST ${bst(m)}</div></div></article>`}
function moveCard(m){return`<article class="card" data-k="m" data-i="${m.__i}"><span class="num">#${m.id}</span><h3>${esc(moveName(m))}</h3><div class="en">${esc(m.name)}</div><div class="badges">${(m.types||[]).map(badge).join('')}<span class="pill">${split(m.split)}</span><span class="pill">위력 ${m.pwr||'—'}</span></div></article>`}
function abCard(a,u){return`<article class="card" data-k="a" data-i="${a.__i}"><div class="card-top"><span class="num">#${a.id}</span>${u?'<span class="unique-label">고유 특성</span>':''}</div><h3>${esc(abilityName(a))}</h3><div class="en">${esc(a.name)}</div></article>`}
function render(){ $$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===S.view));let L={pokemon:['포켓몬','종족값 · 타입 · 특성 · 고유 특성 · 진화 · 폼'],moves:['기술','위력 · 명중 · PP · 습득 포켓몬'],abilities:['특성','일반 특성 · 보유 포켓몬'],innates:['고유 특성','고유 특성 · 보유 포켓몬']}[S.view];$('#title').textContent=L[0];$('#sort').style.display=['abilities','innates'].includes(S.view)?'none':'block';filters();let a=filt(),v=a.slice(0,S.limit);$('#sub').textContent=`${L[1]} · ${a.length.toLocaleString()}개`;$('#grid').className='grid '+(S.view==='pokemon'?'':'text');$('#grid').innerHTML=S.view==='pokemon'?v.map(monCard).join(''):S.view==='moves'?v.map(moveCard).join(''):v.map(x=>abCard(x,S.view==='innates')).join('');$('#empty').classList.toggle('hidden',a.length>0);$('#more').classList.toggle('hidden',a.length<=S.limit);$('#grid').querySelectorAll('[data-k]').forEach(c=>c.onclick=()=>open(c.dataset.k,+c.dataset.i))}
function abBox(i,u){let a=atAb(i);return a?`<button class="ability-box ${u?'unique':''}" data-a="${i}"><b>${esc(abilityName(a))}</b><small>${u?'고유 특성 · ':''}${esc(a.name)}</small></button>`:''}
function evoText(e){let k=String(S.d?.evoKindT?.[e.kd]||'').toUpperCase(),s=String(e.rs??'').replace(/^ITEM_/,'').replace(/^MOVE_/,'').replace(/_/g,' ');if(k.includes('LEVEL'))return s?`레벨 ${s}`:'레벨업';if(k.includes('ITEM'))return s?`${s} 사용`:'도구 사용';if(k.includes('FRIEND'))return'친밀도';if(k.includes('TRADE'))return'통신교환';if(k.includes('MOVE'))return s?`${s} 습득`:'특정 기술 습득';if(k.includes('MAP')||k.includes('LOCATION'))return'특정 장소';if(k.includes('TIME'))return'특정 시간대';return s||'진화 조건'}
function relations(m,form){let a=form?(m.forms||[]).map(x=>({i:+x,t:'폼'})):(m.evolutions||[]).map(x=>({i:+x.in,t:evoText(x)}));return a.map(x=>{let t=atSp(x.i);return t&&t.__i!==m.__i?`<button class="relation-card ${form?'form':''}" data-p="${t.__i}"><span>${esc(x.t)}</span><b>${esc(koName(t))}</b><small>${esc(t.name)}</small></button>`:''}).join('')}
function monDetail(m){let abs=m.stats?.abis||[],uni=m.stats?.inns||[],ev=relations(m,false),fm=relations(m,true),lv=(m.levelUpMoves||[]).map(x=>{let z=atMv(+x.id);return z?`<tr data-m="${z.__i}"><td>${x.lv}</td><td>${esc(moveName(z))}</td><td>${esc(z.name)}</td></tr>`:''}).join('');return`<div class="detail"><div class="detail-head"><img class="detail-sprite" src="${sprite(m)}"><div><div class="card-top"><span class="num">#${m.dex?.id??m.id}</span><span class="origin ${grp(m)}">${gko(m)}</span></div><h1>${esc(koName(m))}</h1><div class="sub">${esc(m.name)}</div><div class="badges">${[...new Set(m.stats?.types||[])].map(badge).join('')}</div></div></div><section class="section"><h2>종족값 · BST ${bst(m)}</h2><div class="stats">${(m.stats?.base||[]).map((v,i)=>`<div class="stat"><span>${SK[i]}</span><b>${v}</b><div class="bar"><i style="width:${Math.min(100,v/2)}%"></i></div></div>`).join('')}</div></section>${abs.length?`<section class="section"><h2>특성</h2><div class="ability-grid">${abs.map(x=>abBox(+x,false)).join('')}</div></section>`:''}${uni.length?`<section class="section"><h2>고유 특성</h2><div class="ability-grid">${uni.map(x=>abBox(+x,true)).join('')}</div></section>`:''}${ev?`<section class="section"><h2>진화</h2><div class="relations">${ev}</div></section>`:''}${fm?`<section class="section"><h2>폼</h2><div class="relations">${fm}</div></section>`:''}${lv?`<section class="section"><h2>레벨업 기술</h2><div class="tablewrap"><table class="table"><thead><tr><th>Lv.</th><th>한국어</th><th>English</th></tr></thead><tbody>${lv}</tbody></table></div></section>`:''}<div class="source">게임 데이터와 연결 구조는 공식 NextDex v2.65beta 기준입니다.</div></div>`}
function moveDetail(m){let i=m.__i,h=S.listSp.filter(p=>(p.levelUpMoves||[]).some(x=>+x.id===i)||(p.tutor||[]).some(x=>+x===i)||(p.TMHMMoves||[]).some(x=>+x===i)||(p.eggMoves||[]).some(x=>+x===i)).slice(0,180);return`<div class="detail"><span class="num">MOVE #${m.id}</span><h1>${esc(moveName(m))}</h1><div class="sub">${esc(m.name)}</div><div class="badges">${(m.types||[]).map(badge).join('')}<span class="pill">${split(m.split)}</span><span class="pill">위력 ${m.pwr||'—'}</span><span class="pill">명중 ${m.acc||'—'}</span><span class="pill">PP ${m.pp??'—'}</span></div><section class="section"><h2>습득 포켓몬</h2><div class="tags">${h.map(p=>`<button class="tag" data-p="${p.__i}">${esc(koName(p))}</button>`).join('')}</div></section><div class="source">수치와 습득 구조는 공식 NextDex v2.65beta 기준입니다.</div></div>`}
function abDetail(a){let i=a.__i,n=S.listSp.filter(p=>(p.stats?.abis||[]).some(x=>+x===i)),u=S.listSp.filter(p=>(p.stats?.inns||[]).some(x=>+x===i));return`<div class="detail"><span class="num">ABILITY #${a.id}</span><h1>${esc(abilityName(a))}</h1><div class="sub">${esc(a.name)}</div>${n.length?`<section class="section"><h2>특성으로 보유</h2><div class="tags">${n.map(p=>`<button class="tag" data-p="${p.__i}">${esc(koName(p))}</button>`).join('')}</div></section>`:''}${u.length?`<section class="section"><h2>고유 특성으로 보유</h2><div class="tags">${u.map(p=>`<button class="tag" data-p="${p.__i}">${esc(koName(p))}</button>`).join('')}</div></section>`:''}<div class="source">보유 관계는 공식 NextDex v2.65beta 기준입니다.</div></div>`}
function open(k,i){let x,h='';if(k==='p'&&(x=atSp(i)))h=monDetail(x);if(k==='m'&&(x=atMv(i)))h=moveDetail(x);if(k==='a'&&(x=atAb(i)))h=abDetail(x);if(!h)return;$('#detail').innerHTML=h;$('#backdrop').classList.remove('hidden');document.body.style.overflow='hidden';$('#detail').querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>open('p',+b.dataset.p));$('#detail').querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>open('m',+b.dataset.m));$('#detail').querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>open('a',+b.dataset.a))}
function close(){ $('#backdrop').classList.add('hidden');document.body.style.overflow=''}
function bind(){ $$('.tab').forEach(b=>b.onclick=()=>{S.view=b.dataset.view;S.type=null;S.sort='id';S.limit=160;$('#sort').value='id';render();scrollTo({top:0,behavior:'smooth'})});$('#groups').querySelectorAll('button').forEach(b=>b.onclick=()=>{S.group=b.dataset.group;S.limit=160;render()});$('#q').oninput=e=>{S.q=e.target.value;render()};$('#sort').onchange=e=>{S.sort=e.target.value;render()};$('#more').onclick=()=>{S.limit+=160;render()};$('#close').onclick=close;$('#backdrop').onclick=e=>e.target===$('#backdrop')&&close();$('#theme').onclick=()=>{document.documentElement.classList.toggle('light');localStorage.setItem('erdex-theme',document.documentElement.classList.contains('light')?'light':'dark')};$('#brand').onclick=()=>{S.view='pokemon';S.group='original';S.q='';S.type=null;$('#q').value='';render()};document.addEventListener('keydown',e=>e.key==='Escape'&&close())}
(async()=>{try{if(localStorage.getItem('erdex-theme')==='light')document.documentElement.classList.add('light')}catch(e){}bind();try{let d=await load();prep(d);render();$('#status').textContent=`공식 NextDex v2.65beta 연결 완료 · 포켓몬/폼 ${S.listSp.length.toLocaleString()}개 · 연결 교정 완료`}catch(e){console.error(e);$('#status').textContent='공식 NextDex 데이터 연결 실패';$('#empty').classList.remove('hidden')}})();
})();
