(()=>{'use strict';
const K=window.KO_DATA,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const URLS=['https://cdn.jsdelivr.net/gh/ForwardFeed/ER-nextdex@main/static/js/data/gameDataV2.65beta.json','https://raw.githubusercontent.com/ForwardFeed/ER-nextdex/main/static/js/data/gameDataV2.65beta.json'];
const COLORS=['#919aa2','#ce416b','#89aae3','#aa6bc8','#d97845','#c5b78c','#91c12f','#5269ad','#5a8ea2','#a57449','#ff9d55','#5a5465','#5090d6','#f4d23c','#73cec0','#fa7179','#0b6dc3','#ec8fe6','#7b6cf6','#666'];
const S={base:null,view:'pokemon',q:'',type:null,sort:'id',limit:160,species:[],moves:[],abilities:[],items:[],trainers:[]};
const esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const norm=s=>String(s??'').toLowerCase().replace(/[\s·._'’\-–—():%]/g,'');
const BASES=Object.entries(K.speciesByEn||{}).filter(([,v])=>v.ko).sort((a,b)=>b[0].length-a[0].length);
const FORM={
'mega':'메가진화','mega x':'메가진화 X','mega y':'메가진화 Y','mega z':'메가진화 Z','redux':'리덕스폼','redux form':'리덕스폼','redux mega':'리덕스 메가진화','redux mega x':'리덕스 메가진화 X','redux mega y':'리덕스 메가진화 Y',
'alola':'알로라의 모습','alolan':'알로라의 모습','galar':'가라르의 모습','galarian':'가라르의 모습','hisui':'히스이의 모습','hisuian':'히스이의 모습','paldea':'팔데아의 모습','paldean':'팔데아의 모습',
'primal':'원시회귀','origin':'오리진폼','altered':'어나더폼','attack':'어택폼','defense':'디펜스폼','speed':'스피드폼','plant cloak':'초목도롱','sandy cloak':'모래땅도롱','trash cloak':'슈레도롱','sunshine':'포지폼','overcast':'네거폼',
'east sea':'동쪽바다','west sea':'서쪽바다','heat':'히트폼','wash':'워시폼','frost':'프로스트폼','fan':'스핀폼','mow':'커트폼','sky':'스카이폼','land':'랜드폼','therian':'영물폼','incarnate':'화신폼','white':'화이트폼','black':'블랙폼',
'resolute':'각오의 모습','ordinary':'평상시 모습','pirouette':'스텝폼','red striped':'적색근의 모습','blue striped':'청색근의 모습','white striped':'백색근의 모습','zen':'달마모드','galar zen':'가라르 달마모드',
'spring':'봄의 모습','summer':'여름의 모습','autumn':'가을의 모습','winter':'겨울의 모습','female':'암컷','male':'수컷','blade':'블레이드폼','shield':'실드폼','small':'작은 사이즈','average':'보통 사이즈','large':'큰 사이즈','super':'특대 사이즈',
'confined':'굴레에 빠진 모습','unbound':'굴레를 벗어난 모습','ash':'지우폼','battle bond':'유대변화','10':'10%폼','10%':'10%폼','50':'50%폼','50%':'50%폼','complete':'퍼펙트폼',
'baile':'이글이글스타일','pom pom':'파칙파칙스타일','pau':'훌라훌라스타일','sensu':'하늘하늘스타일','midday':'한낮의 모습','midnight':'한밤중의 모습','dusk':'황혼의 모습','school':'군집의 모습','solo':'단독의 모습',
'meteor':'유성의 모습','core':'코어의 모습','dusk mane':'황혼의 갈기','dawn wings':'새벽의 날개','ultra':'울트라폼','gulping':'그대로삼킨 모습','gorging':'통째로삼킨 모습','amped':'하이한 모습','low key':'로우한 모습',
'phony':'가품','antique':'진품','ice face':'아이스페이스','noice face':'나이스페이스','hangry':'배고픈 모습','crowned sword':'검왕의 모습','crowned shield':'방패왕의 모습','eternamax':'무한다이맥스',
'single strike':'일격의 태세','rapid strike':'연격의 태세','dada':'아빠 모습','ice rider':'백마 탄 모습','shadow rider':'흑마 탄 모습','family of three':'3마리 가족','family of four':'4마리 가족','hero':'마이티폼','zero':'나이브폼',
'curly':'늘어진 모습','droopy':'처진 모습','stretchy':'뻗은 모습','two segment':'두 마디폼','three segment':'세 마디폼','chest':'상자폼','roaming':'도보폼','counterfeit':'위작','artisan':'고상한 모습','unremarkable':'범작','masterpiece':'걸작',
'teal mask':'벽록의 가면','hearthflame mask':'화덕의 가면','wellspring mask':'우물의 가면','cornerstone mask':'주춧돌의 가면','teal':'벽록의 가면','hearthflame':'화덕의 가면','wellspring':'우물의 가면','cornerstone':'주춧돌의 가면','terastal':'테라스탈폼','stellar':'스텔라폼','bloodmoon':'붉은 달의 모습',
'original cap':'오리지널캡','hoenn cap':'호연캡','sinnoh cap':'신오캡','unova cap':'하나캡','kalos cap':'칼로스캡','alola cap':'알로라캡','partner cap':'너로정했다캡','world cap':'월드캡','gigantamax':'거다이맥스','gmax':'거다이맥스','sunny':'태양의 모습','rainy':'빗방울의 모습','snowy':'설운의 모습','disguised':'둔갑한 모습','busted':'들킨 모습','totem':'주인 포켓몬'
};
function clean(s){return String(s||'').replace(/[_–—-]+/g,' ').replace(/[()]/g,' ').replace(/\s+/g,' ').trim()}
function baseOf(m){const n=String(m.name||'').trim();if(K.speciesByEn[n])return {ko:K.speciesByEn[n].ko,form:''};const low=n.toLowerCase();for(const [en,v] of BASES){const e=en.toLowerCase();if(low===e)return {ko:v.ko,form:''};if(low.startsWith(e+' '))return {ko:v.ko,form:clean(n.slice(en.length))};if(low.endsWith(' '+e))return {ko:v.ko,form:clean(n.slice(0,n.length-en.length))}}const code=String(m.NAME||'').replace(/^SPECIES_/,'');for(const [en,v] of BASES){const c=en.toUpperCase().replace(/[^A-Z0-9]+/g,'_');if(code===c)return {ko:v.ko,form:''};if(code.startsWith(c+'_'))return {ko:v.ko,form:clean(code.slice(c.length+1))}}return null}
function koName(m){const b=baseOf(m);if(!b)return `포켓몬 #${m.id??'?'}`;if(!b.form)return b.ko;let f=clean(b.form).toLowerCase();let tr=FORM[f]||FORM[f.replace(/ form(e)?$/,'')]||'';if(!tr){if(/^mega [xyz]$/.test(f))tr='메가진화 '+f.at(-1).toUpperCase();else if(f==='mega')tr='메가진화';else if(f.includes('mega'))tr='메가진화';else if(f.includes('redux'))tr='리덕스폼';else tr=`특수폼 #${m.id}`}
if(tr==='메가진화')return `메가${b.ko}`;if(/^메가진화 [XYZ]$/.test(tr))return `메가${b.ko}${tr.at(-1)}`;if(tr==='원시회귀')return `원시${b.ko}`;return `${b.ko} (${tr})`}
function tbadge(id){return `<span class="type" style="background:${COLORS[id]||'#666'}">${esc(K.types[id]||`타입${id}`)}</span>`}
function sprite(m){return `https://cdn.jsdelivr.net/gh/ForwardFeed/ER-nextdex@main/static/sprites/${encodeURIComponent(String(m.NAME||'').replace(/^SPECIES_/,''))}.png`}
async function load(){for(const u of URLS){try{const r=await fetch(u,{cache:'force-cache'});if(r.ok)return await r.json()}catch(e){}}return null}
function prep(){const d=S.base||{};S.species=(d.species||[]).filter(x=>x&&x.id>=0);S.moves=(d.moves||[]).filter(Boolean);S.abilities=(d.abilities||[]).filter(Boolean);S.items=(d.items||[]).filter(Boolean);S.trainers=(d.trainers||[]).filter(Boolean);if(!S.species.length)S.species=BASES.map(([name,v])=>({id:v.id,name,NAME:'SPECIES_'+name.toUpperCase().replace(/[^A-Z0-9]+/g,'_'),stats:{base:[],types:[],abis:[],inns:[]}}));if(!S.moves.length)S.moves=Object.values(K.moves);if(!S.abilities.length)S.abilities=Object.values(K.abilities);if(!S.items.length)S.items=Object.values(K.items);if(!S.trainers.length)S.trainers=K.trainers;[['Pokemon',S.species],['Moves',S.moves],['Abilities',S.abilities],['Items',S.items],['Trainers',S.trainers]].forEach(([n,a])=>{const e=$('#count'+n);if(e)e.textContent=a.length.toLocaleString()});$('#heroStats').innerHTML=[['포켓몬',S.species.length],['기술',S.moves.length],['특성',S.abilities.length]].map(([n,c])=>`<div class="hero-stat"><b>${c.toLocaleString()}</b><span>${n}</span></div>`).join('')}
function searchText(v,x){if(v==='pokemon')return koName(x)+' '+(x.name||'');const map=v==='moves'?K.moves:v==='abilities'?K.abilities:v==='items'?K.items:null;const k=map?.[x.id]||x;if(v==='trainers'){const z=K.trainers.find(a=>a.id===x.id)||x;return z.ko||x.name||''}return `${k.ko||x.name||''} ${x.name||''} ${k.short||k.desc||''}`}
function list(){let a=[...(S.view==='pokemon'?S.species:S.view==='moves'?S.moves:S.view==='abilities'?S.abilities:S.view==='items'?S.items:S.trainers)];if(S.q){const q=norm(S.q);a=a.filter(x=>norm(searchText(S.view,x)).includes(q))}if(S.type!==null){if(S.view==='pokemon')a=a.filter(x=>(x.stats?.types||[]).includes(S.type));if(S.view==='moves')a=a.filter(x=>(x.types||[]).includes(S.type))}a.sort((a,b)=>S.sort==='name'?searchText(S.view,a).localeCompare(searchText(S.view,b),'ko'):S.sort==='bst'&&S.view==='pokemon'?bst(b)-bst(a):(a.id??99999)-(b.id??99999));return a}
const bst=m=>(m.stats?.base||[]).reduce((a,b)=>a+(+b||0),0);
function pcard(m){return `<article class="card pokemon-card" data-k="pokemon" data-id="${m.id}"><div class="sprite-box"><img class="sprite" loading="lazy" src="${sprite(m)}" onerror="this.style.display='none'"></div><div><span class="num">#${String(m.dex?.id??m.id).padStart(4,'0')}</span><h3>${esc(koName(m))}</h3><div class="types">${[...new Set(m.stats?.types||[])].map(tbadge).join('')}</div><div class="bst">BST <b>${bst(m)||'—'}</b></div></div></article>`}
function xcard(kind,x){const map=kind==='move'?K.moves:kind==='ability'?K.abilities:kind==='item'?K.items:null,k=map?.[x.id]||x;if(kind==='trainer'){const z=K.trainers.find(a=>a.id===x.id)||x;return `<article class="card text-card" data-k="trainer" data-id="${x.id}"><span class="num">TRAINER #${x.id}</span><h3>${esc(z.ko||x.name||'이름 없음')}</h3></article>`}return `<article class="card text-card" data-k="${kind}" data-id="${x.id}"><span class="num">#${x.id}</span><h3>${esc(k.ko||x.name||'')}</h3>${kind==='move'?`<div class="move-meta">${(x.types||[]).map(tbadge).join('')}<span class="pill">${['물리','특수','변화'][x.split]||''}</span>${x.pwr!==undefined?`<span class="pill">위력 ${x.pwr||'—'}</span>`:''}</div>`:''}<div class="desc">${esc(k.short||k.desc||x.desc||'')}</div></article>`}
function filters(){const e=$('#typeFilters');if(!['pokemon','moves'].includes(S.view)){e.innerHTML='';return}e.innerHTML=`<button class="filter-chip ${S.type===null?'active':''}" data-t="">전체</button>`+K.types.map((n,i)=>`<button class="filter-chip ${S.type===i?'active':''}" data-t="${i}">${esc(n)}</button>`).join('');e.querySelectorAll('button').forEach(b=>b.onclick=()=>{S.type=b.dataset.t===''?null:+b.dataset.t;render()})}
function render(){const titles={pokemon:['포켓몬','종족값 · 타입 · 특성 · Innate · 기술 · 진화'],moves:['기술','한국어 기술명 · 위력 · 타입'],abilities:['특성','한국어 특성 설명'],items:['도구','한국어 도구명 · 설명'],trainers:['트레이너','한국어 트레이너명']};$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===S.view));$('#viewTitle').textContent=titles[S.view][0];filters();const all=list();$('#viewSubtitle').textContent=titles[S.view][1]+` · ${all.length.toLocaleString()}개`;const f=S.view==='pokemon'?pcard:S.view==='moves'?x=>xcard('move',x):S.view==='abilities'?x=>xcard('ability',x):S.view==='items'?x=>xcard('item',x):x=>xcard('trainer',x);$('#results').className='grid '+(S.view==='pokemon'?'':'text-grid');$('#results').innerHTML=all.slice(0,S.limit).map(f).join('');$('#empty').classList.toggle('hidden',!!all.length);$('#sortSelect').style.display=['pokemon','moves'].includes(S.view)?'block':'none';$('#results').querySelectorAll('[data-k]').forEach(e=>e.onclick=()=>detail(e.dataset.k,+e.dataset.id));if(all.length>S.limit){const b=document.createElement('button');b.className='filter-chip';b.style='grid-column:1/-1;margin:12px auto';b.textContent='더 보기';b.onclick=()=>{S.limit+=160;render()};$('#results').appendChild(b)}}
function modal(h){$('#modalContent').innerHTML=h;$('#modalBackdrop').classList.remove('hidden');document.body.style.overflow='hidden'}
function close(){ $('#modalBackdrop').classList.add('hidden');document.body.style.overflow='' }
function detail(kind,id){if(kind==='pokemon'){const m=S.species.find(x=>x.id===id);if(!m)return;const st=m.stats||{},ab=[...(st.abis||[]),...(st.inns||[])];modal(`<div class="detail"><div class="detail-head"><img class="detail-sprite" src="${sprite(m)}"><div><span class="num">SPECIES #${m.id}</span><h1>${esc(koName(m))}</h1><div class="types">${[...new Set(st.types||[])].map(tbadge).join('')}</div><div class="bst">종족값 합계 <b>${bst(m)}</b></div></div></div><div class="section"><h2>종족값</h2><div class="stats">${(st.base||[]).map((v,i)=>`<div class="stat"><span>${K.stats[i]}</span><b>${v}</b><div class="bar"><i style="width:${Math.min(100,v/1.8)}%"></i></div></div>`).join('')}</div></div><div class="section"><h2>특성 / Innate</h2><div class="ability-grid">${ab.map((a,i)=>{const k=K.abilities[a]||{};return `<div class="ability-card"><b>${esc(k.ko||`특성 #${a}`)}</b><span>${i<(st.abis||[]).length?'ABILITY':'INNATE'}</span></div>`}).join('')}</div></div><div class="section"><h2>레벨업 기술</h2><div>${(m.levelUpMoves||[]).map(v=>{const k=K.moves[v.id]||{};return `<span class="tag">Lv.${v.lv} ${esc(k.ko||`기술 #${v.id}`)}</span>`}).join('')||'없음'}</div></div><div class="section"><h2>진화</h2><div>${(m.evolutions||[]).map(e=>{const z=S.species.find(x=>x.id===e.in);return `<span class="tag">${z?esc(koName(z)):`포켓몬 #${e.in}`} · ${esc(e.rs||'')}</span>`}).join('')||'진화 없음'}</div></div></div>`);return}const arr=kind==='move'?S.moves:kind==='ability'?S.abilities:kind==='item'?S.items:S.trainers,x=arr.find(v=>v.id===id);if(!x)return;const map=kind==='move'?K.moves:kind==='ability'?K.abilities:kind==='item'?K.items:null,k=map?.[id]||x;if(kind==='trainer'){const z=K.trainers.find(a=>a.id===id)||x;modal(`<div class="detail-simple"><span class="num">TRAINER #${id}</span><h1>${esc(z.ko||x.name||'이름 없음')}</h1></div>`);return}modal(`<div class="detail-simple"><span class="num">#${id}</span><h1>${esc(k.ko||x.name||'')}</h1>${kind==='move'?`<div class="move-meta">${(x.types||[]).map(tbadge).join('')}<span class="pill">위력 ${x.pwr??'—'}</span><span class="pill">명중 ${x.acc||'—'}</span><span class="pill">PP ${x.pp??'—'}</span></div>`:''}<div class="desc">${esc(k.short||k.desc||x.desc||'설명 없음')}</div></div>`)}
function bind(){$$('.nav').forEach(b=>b.onclick=()=>{S.view=b.dataset.view;S.type=null;S.limit=160;render();window.scrollTo({top:0,behavior:'smooth'})});$('#globalSearch').oninput=e=>{S.q=e.target.value;S.limit=160;render()};$('#sortSelect').onchange=e=>{S.sort=e.target.value;render()};$('#themeBtn').onclick=()=>document.documentElement.classList.toggle('light');$('#modalClose').onclick=close;$('#modalBackdrop').onclick=e=>{if(e.target===$('#modalBackdrop'))close()};$('#homeBtn').onclick=()=>{S.view='pokemon';S.q='';S.type=null;$('#globalSearch').value='';render()}}
async function init(){bind();prep();render();const d=await load();if(d){S.base=d;prep();render();$('#statusText').textContent=`연결 완료 · ${S.species.length.toLocaleString()}종/폼`;$('#statusBar .dot').className='dot'}else{$('#statusText').textContent='공개 전투 데이터 연결 실패 · 한국어 목록만 표시 중';$('#statusBar .dot').className='dot error'}}init();
})();