(()=>{'use strict';
let DATA=null,loading=null,speciesMap=null,mapKoById=null,mapKoByEn=null;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function host(){const body=document.querySelector('.detail-body');if(!body)return null;let box=document.getElementById('stage21EncounterDetail');if(!box){box=document.createElement('section');box.id='stage21EncounterDetail';box.className='detail-section s21-detail';box.hidden=true;const s19=document.getElementById('stage19SpeciesDetail');if(s19)s19.insertAdjacentElement('beforebegin',box);else body.appendChild(box)}return box}
function hide(){const box=document.getElementById('stage21EncounterDetail');if(box)box.hidden=true}
function initMapKo(){const d=window.ER_STAGE22_MAP_KO;if(!d||!Array.isArray(d.maps)){mapKoById=null;mapKoByEn=null;return}mapKoById=new Map(d.maps.map(r=>[Number(r[0]),String(r[2]||'')]));mapKoByEn=new Map(d.maps.map(r=>[String(r[1]||''),String(r[2]||'')]))}
function initMaps(){DATA=window.ER_STAGE21_DATA||null;if(!DATA)throw Error('STAGE21 data missing');speciesMap=new Map((DATA.species||[]).map(r=>[Number(r[0]),r]));initMapKo()}
function ensureData(){if(DATA){if(!mapKoById)initMapKo();return Promise.resolve(DATA)}if(loading)return loading;loading=new Promise((resolve,reject)=>{const existing=document.querySelector('script[data-stage21-data]');if(existing){existing.addEventListener('load',()=>{try{initMaps();resolve(DATA)}catch(e){reject(e)}},{once:true});existing.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src='stage21-data.js?v=20261009-stage21';s.async=false;s.dataset.stage21Data='1';s.onload=()=>{try{initMaps();resolve(DATA)}catch(e){reject(e)}};s.onerror=()=>reject(new Error('STAGE21 data load failed'));document.body.appendChild(s)});return loading}
function mapName(name,mapId){if(!mapKoById)initMapKo();const ko=mapKoById?.get(Number(mapId))||mapKoByEn?.get(String(name||''));if(ko)return ko;const m=String(name||'').match(/^Route\s+(\d+)(.*)$/i);return m?`${m[1]}번도로${m[2]||''}`:String(name||'')}
function lvText(min,max){min=Number(min)||0;max=Number(max)||0;if(!min&&!max)return'';return min===max?`Lv.${min}`:`Lv.${min}–${max}`}
function naturalRow(r){const en=String(r[2]||''),name=mapName(en,r[1]),field=DATA?.meta?.fieldKo?.[r[3]]||r[3],lv=lvText(r[4],r[5]),slots=Number(r[6])||1;return `<div class="s21-row"><div class="s21-place"><strong title="${esc(en)}">${esc(name)}</strong></div><div class="s21-tags"><span>${esc(field)}</span>${lv?`<span>${esc(lv)}</span>`:''}${slots>1?`<span>${slots}슬롯</span>`:''}</div></div>`}
function scriptedRow(r){const en=String(r[1]||''),name=mapName(en,r[0]),label=r[4]||r[3]||'이벤트';return `<div class="s21-row s21-script"><div class="s21-place"><strong title="${esc(en)}">${esc(name)}</strong></div><div class="s21-tags"><span>${esc(label)}</span></div></div>`}
function group(title,rows,renderer){if(!rows.length)return'';return `<section class="s21-group s25-always"><div class="s21-group-head"><strong>${esc(title)}</strong><span>${rows.length.toLocaleString('ko-KR')}곳</span></div><div class="s21-list">${rows.map(renderer).join('')}</div></section>`}
function render(id){const box=host();if(!box)return;const r=speciesMap?.get(Number(id));if(!r){box.hidden=true;return}const natural=Array.isArray(r[3])?r[3]:[],scripted=Array.isArray(r[4])?r[4]:[];if(!natural.length&&!scripted.length){box.hidden=true;return}box.innerHTML=`<div class="s21-head"><h3>출현 · 획득 정보</h3><span>NextDex 2.65.4</span></div>${group('야생 출현',natural,naturalRow)}${group('이벤트 · 지급',scripted,scriptedRow)}<p class="s21-note">트레이너 팀 데이터는 포함하지 않습니다. 장소명은 STAGE22 한국어 지명표를 사용하며, 공식 NextDex의 출현 분류·레벨 범위는 그대로 유지합니다. 빈 예약 슬롯은 제외합니다.</p>`;box.hidden=false}
function show(id){const box=host();if(box){box.innerHTML='<p class="s21-loading">출현·획득 데이터를 불러오는 중…</p>';box.hidden=false}ensureData().then(()=>render(id)).catch(()=>{if(box){box.innerHTML='<p class="s21-empty">출현 데이터를 불러오지 못했습니다.</p>';box.hidden=false}})}
function pickSpeciesTarget(e){const card=e.target.closest?.('.species-card[data-kind="pokemon"]');if(card)return Number(card.dataset.id);const form=e.target.closest?.('.form-link[data-id]');if(form)return Number(form.dataset.id);return 0}
document.addEventListener('click',e=>{const id=pickSpeciesTarget(e);if(id){setTimeout(()=>show(id),0);return}if(e.target.closest?.('.move-card[data-kind]'))hide();const tab=e.target.closest?.('.tab[data-view]');if(tab&&tab.dataset.view!=='pokemon')hide()});
document.addEventListener('keydown',e=>{if(e.key!=='Enter'&&e.key!==' ')return;const id=pickSpeciesTarget(e);if(id)setTimeout(()=>show(id),0)});
window.ER_STAGE21={ensureData,show,hide};
})();
