(()=>{'use strict';
let DATA=null,loading=null,speciesMap=null,moveNames=null,abilityNames=null;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function host(){const body=document.querySelector('.detail-body');if(!body)return null;let box=document.getElementById('stage19SpeciesDetail');if(!box){box=document.createElement('section');box.id='stage19SpeciesDetail';box.className='detail-section s19-detail';box.hidden=true;const extra=document.getElementById('detailPokemonExtra');if(extra)extra.insertAdjacentElement('afterend',box);else body.prepend(box)}return box}
function hide(){const box=document.getElementById('stage19SpeciesDetail');if(box)box.hidden=true}
function initMaps(){DATA=window.ER_STAGE19_DATA||null;if(!DATA)throw Error('STAGE19 data missing');speciesMap=new Map((DATA.species||[]).map(r=>[Number(r[0]),r]));moveNames=new Map((DATA.moveNames||[]).map(r=>[Number(r[0]),String(r[1]||'')]));abilityNames=new Map((DATA.abilityNames||[]).map(r=>[Number(r[0]),String(r[1]||'')]))}
function ensureData(){if(DATA)return Promise.resolve(DATA);if(loading)return loading;loading=new Promise((resolve,reject)=>{const existing=document.querySelector('script[data-stage19-data]');if(existing){existing.addEventListener('load',()=>{try{initMaps();resolve(DATA)}catch(e){reject(e)}},{once:true});existing.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src='stage19-data.js?v=20261009-stage19';s.async=false;s.dataset.stage19Data='1';s.onload=()=>{try{initMaps();resolve(DATA)}catch(e){reject(e)}};s.onerror=()=>reject(new Error('STAGE19 data load failed'));document.body.appendChild(s)});return loading}
function abiChip(id){const n=abilityNames.get(Number(id))||`특성 #${id}`;return `<span class="s19-chip">${esc(n)}<small>#${String(id).padStart(4,'0')}</small></span>`}
function moveChip(id){const n=moveNames.get(Number(id))||`기술 #${id}`;return `<span class="s19-chip">${esc(n)}<small>#${String(id).padStart(4,'0')}</small></span>`}
function levelChip(row){const lv=Number(row[0])||0,id=Number(row[1])||0,n=moveNames.get(id)||`기술 #${id}`;return `<span class="s19-level"><b>Lv.${lv}</b>${esc(n)}<small>#${String(id).padStart(4,'0')}</small></span>`}
function abilityGroup(title,ids){return `<div class="s19-ability-group"><strong>${esc(title)}</strong>${ids.length?`<div class="s19-chips">${ids.map(abiChip).join('')}</div>`:'<p class="s19-empty">공식 데이터 없음</p>'}</div>`}
function moveDetails(title,ids,open=false){if(!ids.length)return'';return `<details class="s19-learn"${open?' open':''}><summary>${esc(title)}<span>${ids.length.toLocaleString('ko-KR')}개</span></summary><div class="s19-moves">${ids.map(moveChip).join('')}</div></details>`}
function levelDetails(rows){if(!rows.length)return'';return `<details class="s19-learn" open><summary>레벨업 기술<span>${rows.length.toLocaleString('ko-KR')}개</span></summary><div class="s19-moves">${rows.map(levelChip).join('')}</div></details>`}
function fold(title,count,body,open=false){return `<details class="s19-block s22-fold"${open?' open':''}><summary><strong>${esc(title)}</strong><span>${Number(count).toLocaleString('ko-KR')}</span></summary><div class="s22-fold-body">${body}</div></details>`}
function render(id){const box=host();if(!box)return;const r=speciesMap?.get(Number(id));if(!r){box.innerHTML='<p class="s19-empty">이 모습의 STAGE19 연결 데이터를 찾지 못했습니다.</p>';box.hidden=false;return}const abis=Array.isArray(r[1])?r[1]:[],inns=Array.isArray(r[2])?r[2]:[],level=Array.isArray(r[3])?r[3]:[],tmhm=Array.isArray(r[4])?r[4]:[],tutor=Array.isArray(r[5])?r[5]:[],egg=Array.isArray(r[6])?r[6]:[];const moveCount=level.length+tmhm.length+tutor.length+egg.length;const abiBody=`<div class="s19-ability-groups">${abilityGroup('선택 특성 (Abilities)',abis)}${abilityGroup('Innate 특성',inns)}</div>`;const moveBody=`${levelDetails(level)}${moveDetails('TM / HM',tmhm)}${moveDetails('기타 습득기술 (Tutor)',tutor)}${moveDetails('교배기',egg)}${!moveCount?'<p class="s19-empty">공식 습득기술 데이터 없음</p>':''}<p class="s19-note">공식 NextDex 2.65.4 원본 분류를 그대로 표시합니다. 현재 원본은 TM/HM·교배기 배열을 비워 두고 비레벨업 습득기를 Tutor 목록에 제공하므로 임의로 재분류하지 않습니다.</p>`;box.innerHTML=`<div class="s19-head"><h3>특성 · 습득기술</h3><span class="s19-source">NextDex 2.65.4</span></div>${fold('보유 특성',abis.length+inns.length,abiBody,true)}${fold('습득기술',moveCount,moveBody,false)}`;box.hidden=false}
function show(id){const box=host();if(box){box.innerHTML='<p class="s19-loading">특성·습득기술 데이터를 불러오는 중…</p>';box.hidden=false}ensureData().then(()=>render(id)).catch(()=>{if(box){box.innerHTML='<p class="s19-empty">STAGE19 데이터를 불러오지 못했습니다.</p>';box.hidden=false}})}
function pickSpeciesTarget(e){const card=e.target.closest?.('.species-card[data-kind="pokemon"]');if(card)return Number(card.dataset.id);const form=e.target.closest?.('.form-link[data-id]');if(form)return Number(form.dataset.id);return 0}
document.addEventListener('click',e=>{const id=pickSpeciesTarget(e);if(id){setTimeout(()=>show(id),0);return}if(e.target.closest?.('.move-card[data-kind]'))hide();const tab=e.target.closest?.('.tab[data-view]');if(tab&&tab.dataset.view!=='pokemon')hide()});
document.addEventListener('keydown',e=>{if(e.key!=='Enter'&&e.key!==' ')return;const id=pickSpeciesTarget(e);if(id)setTimeout(()=>show(id),0)});
window.ER_STAGE19={ensureData,show,hide};
})();
