(()=>{'use strict';
let DATA=null,loading=null,speciesMap=null,moveNames=null,abilityNames=null;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function host(){const body=document.querySelector('.detail-body');if(!body)return null;let box=document.getElementById('stage19SpeciesDetail');if(!box){box=document.createElement('section');box.id='stage19SpeciesDetail';box.className='detail-section s19-detail';box.hidden=true;const extra=document.getElementById('detailPokemonExtra');if(extra)extra.insertAdjacentElement('afterend',box);else body.prepend(box)}return box}
function hide(){const box=document.getElementById('stage19SpeciesDetail');if(box)box.hidden=true}
function initMaps(){DATA=window.ER_STAGE19_DATA||null;if(!DATA)throw Error('STAGE19 data missing');speciesMap=new Map((DATA.species||[]).map(r=>[Number(r[0]),r]));moveNames=new Map((DATA.moveNames||[]).map(r=>[Number(r[0]),String(r[1]||'')]));abilityNames=new Map((DATA.abilityNames||[]).map(r=>[Number(r[0]),String(r[1]||'')]))}
function ensureData(){if(DATA)return Promise.resolve(DATA);if(loading)return loading;loading=new Promise((resolve,reject)=>{const existing=document.querySelector('script[data-stage19-data]');if(existing){existing.addEventListener('load',()=>{try{initMaps();resolve(DATA)}catch(e){reject(e)}},{once:true});existing.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src='stage19-data.js?v=20261009-stage19';s.async=false;s.dataset.stage19Data='1';s.onload=()=>{try{initMaps();resolve(DATA)}catch(e){reject(e)}};s.onerror=()=>reject(new Error('STAGE19 data load failed'));document.body.appendChild(s)});return loading}
function abiChip(id){const n=abilityNames.get(Number(id))||`특성 #${id}`;return `<button type="button" class="s19-chip s19-detail-link" data-detail-kind="abilities" data-detail-id="${Number(id)}" aria-label="${esc(n)} 특성 설명 보기"><span>${esc(n)}</span><small>#${String(id).padStart(4,'0')}</small></button>`}
function moveChip(id){const n=moveNames.get(Number(id))||`기술 #${id}`;return `<button type="button" class="s19-chip s19-detail-link" data-detail-kind="moves" data-detail-id="${Number(id)}" aria-label="${esc(n)} 기술 설명 보기"><span>${esc(n)}</span><small>#${String(id).padStart(4,'0')}</small></button>`}
function levelChip(row){const lv=Number(row[0])||0,id=Number(row[1])||0,n=moveNames.get(id)||`기술 #${id}`;return `<button type="button" class="s19-level s19-detail-link" data-detail-kind="moves" data-detail-id="${id}" aria-label="${esc(n)} 기술 설명 보기"><b>Lv.${lv}</b><span>${esc(n)}</span><small>#${String(id).padStart(4,'0')}</small></button>`}
function abilityGroup(title,ids){return `<div class="s19-ability-group"><strong>${esc(title)}</strong>${ids.length?`<div class="s19-chips">${ids.map(abiChip).join('')}</div>`:'<p class="s19-empty">데이터 없음</p>'}</div>`}
function moveGroup(title,ids){if(!ids.length)return'';return `<section class="s19-learn"><div class="s19-learn-head"><strong>${esc(title)}</strong><span>${ids.length.toLocaleString('ko-KR')}개</span></div><div class="s19-moves">${ids.map(moveChip).join('')}</div></section>`}
function levelGroup(rows){if(!rows.length)return'';return `<section class="s19-learn"><div class="s19-learn-head"><strong>레벨업 기술</strong><span>${rows.length.toLocaleString('ko-KR')}개</span></div><div class="s19-moves">${rows.map(levelChip).join('')}</div></section>`}
function block(title,count,body){return `<section class="s19-block s25-always"><div class="s19-block-title"><strong>${esc(title)}</strong><span>${Number(count).toLocaleString('ko-KR')}</span></div><div class="s19-block-body">${body}</div></section>`}
function render(id){const box=host();if(!box)return;const r=speciesMap?.get(Number(id));if(!r){box.innerHTML='<p class="s19-empty">이 모습의 연결 데이터를 찾지 못했습니다.</p>';box.hidden=false;return}const abis=Array.isArray(r[1])?r[1]:[],inns=Array.isArray(r[2])?r[2]:[],level=Array.isArray(r[3])?r[3]:[],tmhm=Array.isArray(r[4])?r[4]:[],tutor=Array.isArray(r[5])?r[5]:[],egg=Array.isArray(r[6])?r[6]:[];const moveCount=level.length+tmhm.length+tutor.length+egg.length;const abiBody=`<div class="s19-ability-groups">${abilityGroup('특성',abis)}${abilityGroup('고유 특성',inns)}</div>`;const moveBody=`${levelGroup(level)}${moveGroup('TM / HM',tmhm)}${moveGroup('기타 습득기술',tutor)}${moveGroup('교배기',egg)}${!moveCount?'<p class="s19-empty">습득기술 데이터 없음</p>':''}`;box.innerHTML=`<div class="s19-head"><h3>특성 · 습득기술</h3></div>${block('보유 특성',abis.length+inns.length,abiBody)}${block('습득기술',moveCount,moveBody)}`;box.hidden=false}
function show(id){const box=host();if(box){box.innerHTML='<p class="s19-loading">특성·습득기술 데이터를 불러오는 중…</p>';box.hidden=false}ensureData().then(()=>render(id)).catch(()=>{if(box){box.innerHTML='<p class="s19-empty">특성·습득기술 데이터를 불러오지 못했습니다.</p>';box.hidden=false}})}
function pickSpeciesTarget(e){const card=e.target.closest?.('.species-card[data-kind="pokemon"]');if(card)return Number(card.dataset.id);const form=e.target.closest?.('.form-link[data-id]');if(form)return Number(form.dataset.id);return 0}
document.addEventListener('click',e=>{const link=e.target.closest?.('.s19-detail-link[data-detail-kind][data-detail-id]');if(link){e.preventDefault();window.ER_STAGE25_DETAIL?.open(String(link.dataset.detailKind),Number(link.dataset.detailId));return}const id=pickSpeciesTarget(e);if(id){setTimeout(()=>show(id),0);return}if(e.target.closest?.('.move-card[data-kind]'))hide();const tab=e.target.closest?.('.tab[data-view]');if(tab&&tab.dataset.view!=='pokemon')hide()});
document.addEventListener('keydown',e=>{if(e.key!=='Enter'&&e.key!==' ')return;const id=pickSpeciesTarget(e);if(id)setTimeout(()=>show(id),0)});
window.ER_STAGE19={ensureData,show,hide};
})();
