(()=>{'use strict';
const MOVE_META=new Map((Array.isArray(window.ER_MOVE_META)?window.ER_MOVE_META:[]).map(r=>[Number(r[0]),r]));
const ABILITY_META=new Map((Array.isArray(window.ER_ABILITY_META)?window.ER_ABILITY_META:[]).map(r=>[Number(r[0]),r]));
const TYPE_KO={Normal:'노말',Fire:'불꽃',Water:'물',Electric:'전기',Grass:'풀',Ice:'얼음',Fighting:'격투',Poison:'독',Ground:'땅',Flying:'비행',Psychic:'에스퍼',Bug:'벌레',Rock:'바위',Ghost:'고스트',Dragon:'드래곤',Dark:'악',Steel:'강철',Fairy:'페어리',Stellar:'스텔라'};
const SPLIT_KO={PHYSICAL:'물리',SPECIAL:'특수',STATUS:'변화'};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function moveMetaHtml(r,compact=false){if(!r)return'';const type=TYPE_KO[r[3]]||r[3]||'—',split=SPLIT_KO[r[4]]||r[4]||'—',power=Number(r[5])||0,acc=Number(r[6])||0,pp=Number(r[7])||0,prio=Number(r[8])||0;return `<div class="s18-move-meta${compact?' compact':''}"><span class="s18-type" data-type="${esc(type)}">${esc(type)}</span><span>${esc(split)}</span><span><i>위력</i><b>${power||'—'}</b></span><span><i>명중</i><b>${acc?acc:'—'}</b></span><span><i>PP</i><b>${pp||'—'}</b></span>${prio?`<span><i>우선도</i><b>${prio>0?'+':''}${prio}</b></span>`:''}</div>`}
function augmentCards(root=document){root.querySelectorAll('.move-card[data-kind]').forEach(card=>{if(card.dataset.s18==='1')return;const id=Number(card.dataset.id),kind=card.dataset.kind;if(kind==='moves'){const r=MOVE_META.get(id);if(!r)return;const ko=card.querySelector('.ko');if(ko)ko.insertAdjacentHTML('afterend',`<div class="s18-en">${esc(r[1])}</div>${moveMetaHtml(r,true)}`)}else if(kind==='abilities'){const r=ABILITY_META.get(id);if(!r)return;const ko=card.querySelector('.ko');if(ko)ko.insertAdjacentHTML('afterend',`<div class="s18-en">${esc(r[1])}</div>`)}card.dataset.s18='1'})}
function detailHost(){const body=document.querySelector('.detail-body');if(!body)return null;let box=document.getElementById('stage18Meta');if(!box){box=document.createElement('section');box.id='stage18Meta';box.className='detail-section s18-detail';const extra=document.getElementById('detailPokemonExtra');if(extra)extra.insertAdjacentElement('afterend',box);else body.prepend(box)}return box}
function hideDetailMeta(){const box=document.getElementById('stage18Meta');if(box)box.hidden=true}
function augmentDetail(kind,id){if(kind!=='moves'&&kind!=='abilities'){hideDetailMeta();return}const box=detailHost();if(!box)return;if(kind==='moves'){const r=MOVE_META.get(id);if(!r){box.hidden=true;return}const chance=Number(r[9])||0,target=r[10]||'',officialShort=r[11]||'',officialLong=r[12]||'';box.innerHTML=`<h3>공식 NextDex 2.65.4 데이터</h3><div class="s18-official-name">${esc(r[1])}<small>${esc(r[2])}</small></div>${moveMetaHtml(r)}${chance?`<p class="s18-sub">부가 효과 확률 <b>${chance}%</b></p>`:''}${target?`<p class="s18-sub">대상 <b>${esc(target)}</b></p>`:''}${officialShort?`<details class="s18-original"><summary>공식 영문 설명</summary><p>${esc(officialShort)}</p>${officialLong&&officialLong!==officialShort?`<p>${esc(officialLong)}</p>`:''}</details>`:''}`;box.hidden=false}else{const r=ABILITY_META.get(id);if(!r){box.hidden=true;return}box.innerHTML=`<h3>공식 NextDex 2.65.4 데이터</h3><div class="s18-official-name">${esc(r[1])}</div>${r[2]?`<details class="s18-original"><summary>공식 영문 설명</summary><p>${esc(r[2])}</p></details>`:''}`;box.hidden=false}}
function handleDetailTrigger(card){if(!card)return;const kind=card.dataset.kind,id=Number(card.dataset.id);if(kind==='pokemon'){hideDetailMeta();return}setTimeout(()=>augmentDetail(kind,id),0)}
const grid=document.getElementById('grid');if(grid){new MutationObserver(()=>augmentCards(grid)).observe(grid,{childList:true,subtree:true});augmentCards(grid)}
document.addEventListener('click',e=>handleDetailTrigger(e.target.closest?.('[data-kind]')));
document.addEventListener('keydown',e=>{if(e.key!=='Enter'&&e.key!==' ')return;handleDetailTrigger(e.target.closest?.('[data-kind]'))});
window.ER_STAGE18={moves:MOVE_META.size,abilities:ABILITY_META.size,augmentCards,augmentDetail,hideDetailMeta};
})();
