(()=>{'use strict';
let DATA=null,loading=null,moveMap=null,abilityMap=null,moveMeta=null,abilityMeta=null,lastFocus=null;
const TYPE_KO={Normal:'노말',Fire:'불꽃',Water:'물',Electric:'전기',Grass:'풀',Ice:'얼음',Fighting:'격투',Poison:'독',Ground:'땅',Flying:'비행',Psychic:'에스퍼',Bug:'벌레',Rock:'바위',Ghost:'고스트',Dragon:'드래곤',Dark:'악',Steel:'강철',Fairy:'페어리',Stellar:'스텔라'};
const SPLIT_KO={PHYSICAL:'물리',SPECIAL:'특수',STATUS:'변화'};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function init(){DATA=window.ER_STAGE25_DETAIL_DATA||null;if(!DATA)throw Error('STAGE25 detail data missing');moveMap=new Map((DATA.moves||[]).map(r=>[Number(r[0]),r]));abilityMap=new Map((DATA.abilities||[]).map(r=>[Number(r[0]),r]));moveMeta=new Map((Array.isArray(window.ER_MOVE_META)?window.ER_MOVE_META:[]).map(r=>[Number(r[0]),r]));abilityMeta=new Map((Array.isArray(window.ER_ABILITY_META)?window.ER_ABILITY_META:[]).map(r=>[Number(r[0]),r]))}
function ensureData(){if(DATA)return Promise.resolve(DATA);if(loading)return loading;loading=new Promise((resolve,reject)=>{const old=document.querySelector('script[data-stage25-detail-data]');if(old){old.addEventListener('load',()=>{try{init();resolve(DATA)}catch(e){reject(e)}},{once:true});old.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src='stage25-detail-data.js?v=20261009-stage25';s.async=false;s.dataset.stage25DetailData='1';s.onload=()=>{try{init();resolve(DATA)}catch(e){reject(e)}};s.onerror=()=>reject(new Error('STAGE25 detail data load failed'));document.body.appendChild(s)});return loading}
function ensureModal(){let bd=document.getElementById('s25ReferenceBackdrop');if(bd)return bd;bd=document.createElement('div');bd.id='s25ReferenceBackdrop';bd.className='detail-backdrop s25-reference-backdrop';bd.hidden=true;bd.innerHTML='<section class="detail-dialog s25-reference-dialog" role="dialog" aria-modal="true" aria-labelledby="s25ReferenceTitle"><div class="detail-top"><div><div id="s25ReferenceType" class="detail-type"></div><h2 id="s25ReferenceTitle" class="detail-title"></h2></div><button id="s25ReferenceClose" class="detail-close" type="button" aria-label="기술 또는 특성 설명 닫기">×</button></div><div id="s25ReferenceBody" class="detail-body"></div></section>';document.body.appendChild(bd);bd.querySelector('#s25ReferenceClose')?.addEventListener('click',close);bd.addEventListener('click',e=>{if(e.target===bd)close()});return bd}
function close(){const bd=document.getElementById('s25ReferenceBackdrop');if(!bd||bd.hidden)return;bd.hidden=true;const pokemon=document.getElementById('detailBackdrop');if(!pokemon||pokemon.hidden)document.body.classList.remove('modal-open');if(lastFocus?.isConnected)lastFocus.focus();lastFocus=null}
function moveMetaHtml(id){const r=moveMeta?.get(Number(id));if(!r)return'';const type=TYPE_KO[r[3]]||r[3]||'—',split=SPLIT_KO[r[4]]||r[4]||'—',power=Number(r[5])||0,acc=Number(r[6])||0,pp=Number(r[7])||0,prio=Number(r[8])||0,chance=Number(r[9])||0,target=String(r[10]||'');return `<section class="detail-section s25-reference-meta"><h3>기술 정보</h3><div class="s25-ref-official">${esc(r[1]||'')}</div><div class="s25-ref-grid"><span><i>타입</i><b>${esc(type)}</b></span><span><i>분류</i><b>${esc(split)}</b></span><span><i>위력</i><b>${power||'—'}</b></span><span><i>명중</i><b>${acc||'—'}</b></span><span><i>PP</i><b>${pp||'—'}</b></span>${prio?`<span><i>우선도</i><b>${prio>0?'+':''}${prio}</b></span>`:''}${chance?`<span><i>부가효과</i><b>${chance}%</b></span>`:''}${target?`<span><i>대상</i><b>${esc(target)}</b></span>`:''}</div></section>`}
function abilityMetaHtml(id){const r=abilityMeta?.get(Number(id));if(!r)return'';return `<section class="detail-section s25-reference-meta"><h3>특성 정보</h3><div class="s25-ref-official">${esc(r[1]||'')}</div></section>`}
function render(kind,id){const isMove=kind==='moves',row=(isMove?moveMap:abilityMap)?.get(Number(id));if(!row)return;const bd=ensureModal(),type=bd.querySelector('#s25ReferenceType'),title=bd.querySelector('#s25ReferenceTitle'),body=bd.querySelector('#s25ReferenceBody'),closeBtn=bd.querySelector('#s25ReferenceClose');type.textContent=`${isMove?'기술':'특성'} · ${isMove?'MOVE':'ABILITY'} #${String(id).padStart(4,'0')}`;title.textContent=String(row[1]||`${isMove?'기술':'특성'} #${id}`);body.innerHTML=`${isMove?moveMetaHtml(id):abilityMetaHtml(id)}<section class="detail-section"><h3>요약 설명</h3><p class="detail-text">${esc(row[2]||'요약 설명이 없습니다.')}</p></section><section class="detail-section"><h3>상세 설명</h3><p class="detail-text">${esc(row[3]||row[2]||'상세 설명이 없습니다.')}</p></section>`;lastFocus=document.activeElement;bd.hidden=false;document.body.classList.add('modal-open');const dialog=bd.querySelector('.s25-reference-dialog');if(dialog)dialog.scrollTop=0;closeBtn?.focus()}
function open(kind,id){kind=String(kind||'');id=Number(id)||0;if((kind!=='moves'&&kind!=='abilities')||!id)return;ensureData().then(()=>render(kind,id)).catch(()=>{const bd=ensureModal(),body=bd.querySelector('#s25ReferenceBody');bd.querySelector('#s25ReferenceType').textContent='설명';bd.querySelector('#s25ReferenceTitle').textContent='데이터를 불러오지 못했습니다';body.innerHTML='<section class="detail-section"><p class="detail-text">다시 시도해 주세요.</p></section>';bd.hidden=false;document.body.classList.add('modal-open')})}
document.addEventListener('keydown',e=>{const bd=document.getElementById('s25ReferenceBackdrop');if(e.key==='Escape'&&bd&&!bd.hidden){e.preventDefault();e.stopImmediatePropagation();close()}},true);
window.ER_STAGE25_DETAIL={ensureData,open,close};
})();
