(()=>{'use strict';
let DATA=null,loading=null,moveMap=null,abilityMap=null;
function init(){DATA=window.ER_STAGE25_DETAIL_DATA||null;if(!DATA)throw Error('STAGE25 detail data missing');moveMap=new Map((DATA.moves||[]).map(r=>[Number(r[0]),r]));abilityMap=new Map((DATA.abilities||[]).map(r=>[Number(r[0]),r]))}
function ensureData(){if(DATA)return Promise.resolve(DATA);if(loading)return loading;loading=new Promise((resolve,reject)=>{const old=document.querySelector('script[data-stage25-detail-data]');if(old){old.addEventListener('load',()=>{try{init();resolve(DATA)}catch(e){reject(e)}},{once:true});old.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src='stage25-detail-data.js?v=20261009-stage25';s.async=false;s.dataset.stage25DetailData='1';s.onload=()=>{try{init();resolve(DATA)}catch(e){reject(e)}};s.onerror=()=>reject(new Error('STAGE25 detail data load failed'));document.body.appendChild(s)});return loading}
function backdrop(){return document.getElementById('detailBackdrop')}
function setReferenceMode(on){backdrop()?.classList.toggle('s25-reference-mode',!!on)}
function hidePokemonSections(){window.ER_STAGE19?.hide?.();window.ER_STAGE20?.hide?.();window.ER_STAGE21?.hide?.();const extra=document.getElementById('detailPokemonExtra'),forms=document.getElementById('detailFormsSection');if(extra){extra.hidden=true;extra.innerHTML=''}if(forms){forms.hidden=true;const g=document.getElementById('detailForms');if(g)g.innerHTML=''}}
function render(kind,id){const isMove=kind==='moves',row=(isMove?moveMap:abilityMap)?.get(Number(id));if(!row)return;setReferenceMode(true);hidePokemonSections();const type=document.getElementById('detailType'),title=document.getElementById('detailTitle'),shortLabel=document.getElementById('detailShortLabel'),short=document.getElementById('detailShort'),longLabel=document.getElementById('detailLongLabel'),long=document.getElementById('detailLong'),bd=backdrop(),close=document.getElementById('detailClose');if(!type||!title||!shortLabel||!short||!longLabel||!long||!bd)return;type.textContent=`${isMove?'기술':'특성'} · ${isMove?'MOVE':'ABILITY'} #${String(id).padStart(4,'0')}`;title.textContent=String(row[1]||`${isMove?'기술':'특성'} #${id}`);shortLabel.textContent='요약 설명';short.textContent=String(row[2]||'요약 설명이 없습니다.');longLabel.textContent='상세 설명';long.textContent=String(row[3]||row[2]||'상세 설명이 없습니다.');bd.hidden=false;document.body.classList.add('modal-open');window.ER_STAGE18?.augmentDetail?.(kind,Number(id));const dialog=bd.querySelector('.detail-dialog');if(dialog)dialog.scrollTop=0;close?.focus()}
function open(kind,id){kind=String(kind||'');id=Number(id)||0;if((kind!=='moves'&&kind!=='abilities')||!id)return;setReferenceMode(true);hidePokemonSections();ensureData().then(()=>render(kind,id)).catch(()=>{const short=document.getElementById('detailShort'),long=document.getElementById('detailLong');if(short)short.textContent='설명 데이터를 불러오지 못했습니다.';if(long)long.textContent='다시 시도해 주세요.'})}
function isPokemonTarget(target){return !!target?.closest?.('.species-card[data-kind="pokemon"],.form-link[data-id],.s20-evo-target[data-id]')}
document.addEventListener('click',e=>{if(isPokemonTarget(e.target))setReferenceMode(false);const tab=e.target.closest?.('.tab[data-view]');if(tab)setReferenceMode(false)},true);
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&isPokemonTarget(e.target))setReferenceMode(false)},true);
window.ER_STAGE25_DETAIL={ensureData,open,setReferenceMode};
})();
