(()=>{'use strict';
let DATA=null,loading=null,speciesMap=null;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function host(){const body=document.querySelector('.detail-body');if(!body)return null;let box=document.getElementById('stage20EvolutionDetail');if(!box){box=document.createElement('section');box.id='stage20EvolutionDetail';box.className='detail-section s20-detail';box.hidden=true;const s19=document.getElementById('stage19SpeciesDetail');if(s19)s19.insertAdjacentElement('beforebegin',box);else{const extra=document.getElementById('detailPokemonExtra');if(extra)extra.insertAdjacentElement('afterend',box);else body.prepend(box)}}return box}
function hide(){const box=document.getElementById('stage20EvolutionDetail');if(box)box.hidden=true}
function initMaps(){DATA=window.ER_STAGE20_DATA||null;if(!DATA)throw Error('STAGE20 data missing');speciesMap=new Map((DATA.species||[]).map(r=>[Number(r[0]),r]))}
function ensureData(){if(DATA)return Promise.resolve(DATA);if(loading)return loading;loading=new Promise((resolve,reject)=>{const existing=document.querySelector('script[data-stage20-data]');if(existing){existing.addEventListener('load',()=>{try{initMaps();resolve(DATA)}catch(e){reject(e)}},{once:true});existing.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src='stage20-data.js?v=20261009-stage20';s.async=false;s.dataset.stage20Data='1';s.onload=()=>{try{initMaps();resolve(DATA)}catch(e){reject(e)}};s.onerror=()=>reject(new Error('STAGE20 data load failed'));document.body.appendChild(s)});return loading}
function condition(kind,reason,reasonKo){switch(kind){case'EVO_LEVEL':return`Lv.${esc(reason)}에 진화`;case'EVO_LEVEL_FEMALE':return`암컷일 때 Lv.${esc(reason)}에 진화`;case'EVO_LEVEL_MALE':return`수컷일 때 Lv.${esc(reason)}에 진화`;case'EVO_MOVE_MEGA_EVOLUTION':return`${esc(reasonKo||reason)}를 배운 상태에서 메가진화`;case'EVO_MEGA_EVOLUTION':return'전용 아이템으로 메가진화';case'EVO_PRIMAL_REVERSION':return'전용 아이템으로 특수 변화';default:return esc(reason||kind)}}
function relationCard(rel,special=false){const id=Number(rel[0]),kind=String(rel[1]||''),reason=String(rel[2]||''),reasonKo=String(rel[3]||''),target=speciesMap.get(id),ko=target?.[1]||`포켓몬 #${id}`,en=target?.[2]||'';const code=special&&reason.startsWith('ITEM_')?`<small class="s20-code">${esc(reason)}</small>`:'';return `<button class="s20-evo-target" type="button" data-id="${id}"><span class="s20-name"><strong>${esc(ko)}</strong>${en?`<small>${esc(en)}</small>`:''}</span><span class="s20-cond">${condition(kind,reason,reasonKo)}${code}</span><span class="s20-go" aria-hidden="true">›</span></button>`}
function relationGroup(title,rows,special=false){if(!rows.length)return'';return `<div class="s20-group"><h5>${esc(title)}</h5><div class="s20-list">${rows.map(r=>relationCard(r,special)).join('')}</div></div>`}
function block(title,incoming,outgoing,special=false){if(!incoming.length&&!outgoing.length)return'';const count=incoming.length+outgoing.length;return `<details class="s20-block${special?' s20-special':''} s22-fold"${special?'':' open'}><summary><strong>${esc(title)}</strong><span>${count.toLocaleString('ko-KR')}개</span></summary><div class="s22-fold-body">${relationGroup(special?'기본 · 이전 형태':'이전 단계',incoming,special)}${relationGroup(special?'변화 후':'진화 후',outgoing,special)}</div></details>`}
function render(id){const box=host();if(!box)return;const r=speciesMap?.get(Number(id));if(!r){box.hidden=true;return}const ordinaryOut=Array.isArray(r[3])?r[3]:[],ordinaryIn=Array.isArray(r[4])?r[4]:[],specialOut=Array.isArray(r[5])?r[5]:[],specialIn=Array.isArray(r[6])?r[6]:[];if(!ordinaryOut.length&&!ordinaryIn.length&&!specialOut.length&&!specialIn.length){box.hidden=true;return}box.innerHTML=`<div class="s20-head"><h3>진화 정보</h3><span>NextDex 2.65.4</span></div>${block('진화',ordinaryIn,ordinaryOut,false)}${block('메가 · 특수 변화',specialIn,specialOut,true)}${specialOut.length||specialIn.length?'<p class="s20-note">도구·아이템 도감은 별도로 제공하지 않습니다. 메가·특수 변화의 아이템 조건은 공식 NextDex 원본 코드를 보조 표기하며, 원본에서 진화 대상이 미설정(-1)인 예약 데이터 2건은 표시하지 않습니다.</p>':''}`;box.hidden=false}
function show(id){const box=host();if(box){box.innerHTML='<p class="s20-loading">진화 데이터를 불러오는 중…</p>';box.hidden=false}ensureData().then(()=>render(id)).catch(()=>{if(box){box.innerHTML='<p class="s20-empty">STAGE20 진화 데이터를 불러오지 못했습니다.</p>';box.hidden=false}})}
function pickSpeciesTarget(e){const card=e.target.closest?.('.species-card[data-kind="pokemon"]');if(card)return Number(card.dataset.id);const form=e.target.closest?.('.form-link[data-id]');if(form)return Number(form.dataset.id);return 0}
function openPokemon(id){const forms=document.getElementById('detailForms');if(!forms)return;const b=document.createElement('button');b.type='button';b.className='form-link';b.dataset.id=String(id);b.hidden=true;forms.appendChild(b);b.click();b.remove()}
document.addEventListener('click',e=>{const evo=e.target.closest?.('.s20-evo-target[data-id]');if(evo){e.preventDefault();openPokemon(Number(evo.dataset.id));return}const id=pickSpeciesTarget(e);if(id){setTimeout(()=>show(id),0);return}if(e.target.closest?.('.move-card[data-kind]'))hide();const tab=e.target.closest?.('.tab[data-view]');if(tab&&tab.dataset.view!=='pokemon')hide()});
document.addEventListener('keydown',e=>{if(e.key!=='Enter'&&e.key!==' ')return;const id=pickSpeciesTarget(e);if(id)setTimeout(()=>show(id),0)});
window.ER_STAGE20={ensureData,show,hide};
})();
